package view;

import dao.OcorrenciaDAO;
import dao.SalvamentoDAO;
import database.Utilitarios;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Ocorrencia;
import model.Salvamento;

/**
 *
 * @author Alunos
 */
public class JFrameListaSalvamento extends javax.swing.JFrame {

    /**
     * Creates new form JFrameListaSalvamento
     */
    public JFrameListaSalvamento() {
        initComponents();
        popularListaSalvamento();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelSalvamento = new javax.swing.JPanel();
        jButtonEditarSalvamento = new javax.swing.JButton();
        jTextFieldPesquisaSalvamento = new javax.swing.JTextField();
        jComboBoxPesquisaSalvamento = new javax.swing.JComboBox();
        jScrollPaneSalvamento = new javax.swing.JScrollPane();
        jTableSalvamento = new javax.swing.JTable();
        jButtonPesquisaSalvamento = new javax.swing.JButton();
        jLabelPesquisaSalvamento = new javax.swing.JLabel();
        jButtonSair = new javax.swing.JButton();
        jLabelListaSalvamento = new javax.swing.JLabel();
        jPanelMenu = new javax.swing.JPanel();
        btnHome1 = new javax.swing.JPanel();
        jLabelBtnHome7 = new javax.swing.JLabel();
        btnListaOcorrencia = new javax.swing.JPanel();
        jLabelBtnListaOcorrencia = new javax.swing.JLabel();
        btnListaSalvamento = new javax.swing.JPanel();
        jLabelBtnListaSalvamento = new javax.swing.JLabel();
        btnListaAbrigo = new javax.swing.JPanel();
        jLabelBtnListaAbrigo = new javax.swing.JLabel();
        btnListaVeiculo = new javax.swing.JPanel();
        jLabelBtnListaVeiculo = new javax.swing.JLabel();
        btnListaDadosGerais = new javax.swing.JPanel();
        jLabelBtnDadosGerais = new javax.swing.JLabel();
        jPanelHome = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("LIsta de Salvamentos");
        setBounds(new java.awt.Rectangle(800, 600, 0, 0));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanelSalvamento.setPreferredSize(new java.awt.Dimension(620, 600));

        jButtonEditarSalvamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/edit-515151-64px.png"))); // NOI18N
        jButtonEditarSalvamento.setToolTipText("Editar salvamento");
        jButtonEditarSalvamento.setBorderPainted(false);
        jButtonEditarSalvamento.setContentAreaFilled(false);
        jButtonEditarSalvamento.setDisabledIcon(null);
        jButtonEditarSalvamento.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/edit-a9cb73-64px.png"))); // NOI18N
        jButtonEditarSalvamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarSalvamentoActionPerformed(evt);
            }
        });

        jTextFieldPesquisaSalvamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPesquisaSalvamentoActionPerformed(evt);
            }
        });

        jComboBoxPesquisaSalvamento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Código", "Veiculo Utilizado", "Cod. Ocorrencia", "Data", "Hora", "Local", "Salvador" }));
        jComboBoxPesquisaSalvamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPesquisaSalvamentoActionPerformed(evt);
            }
        });

        jTableSalvamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Cód. Salvamento", "Cód. Ocorrência", "Data", "Hora", "Local", "Nome", "Veiculo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableSalvamento.setGridColor(new java.awt.Color(81, 81, 81));
        jTableSalvamento.setIntercellSpacing(new java.awt.Dimension(1, 2));
        jTableSalvamento.setSelectionBackground(new java.awt.Color(169, 203, 115));
        jTableSalvamento.setShowVerticalLines(false);
        jTableSalvamento.getTableHeader().setResizingAllowed(false);
        jTableSalvamento.getTableHeader().setReorderingAllowed(false);
        jScrollPaneSalvamento.setViewportView(jTableSalvamento);
        if (jTableSalvamento.getColumnModel().getColumnCount() > 0) {
            jTableSalvamento.getColumnModel().getColumn(0).setResizable(false);
            jTableSalvamento.getColumnModel().getColumn(1).setResizable(false);
            jTableSalvamento.getColumnModel().getColumn(2).setResizable(false);
            jTableSalvamento.getColumnModel().getColumn(3).setResizable(false);
            jTableSalvamento.getColumnModel().getColumn(4).setResizable(false);
            jTableSalvamento.getColumnModel().getColumn(5).setResizable(false);
            jTableSalvamento.getColumnModel().getColumn(6).setResizable(false);
        }

        jButtonPesquisaSalvamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/search-515151-32px.png"))); // NOI18N
        jButtonPesquisaSalvamento.setToolTipText("Pesquisar Salvamento");
        jButtonPesquisaSalvamento.setBorderPainted(false);
        jButtonPesquisaSalvamento.setContentAreaFilled(false);
        jButtonPesquisaSalvamento.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/search-a9cb73-32px.png"))); // NOI18N
        jButtonPesquisaSalvamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisaSalvamentoActionPerformed(evt);
            }
        });

        jLabelPesquisaSalvamento.setText("Pesquisar por:");

        jButtonSair.setBackground(new java.awt.Color(81, 81, 81));
        jButtonSair.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jButtonSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/cancel-515151-64px.png"))); // NOI18N
        jButtonSair.setToolTipText("Sair");
        jButtonSair.setBorderPainted(false);
        jButtonSair.setContentAreaFilled(false);
        jButtonSair.setPreferredSize(new java.awt.Dimension(40, 40));
        jButtonSair.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/cancel-a9cb73-64px.png"))); // NOI18N
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        jLabelListaSalvamento.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabelListaSalvamento.setForeground(new java.awt.Color(81, 81, 81));
        jLabelListaSalvamento.setText("LISTA de SALVAMENTOS");

        javax.swing.GroupLayout jPanelSalvamentoLayout = new javax.swing.GroupLayout(jPanelSalvamento);
        jPanelSalvamento.setLayout(jPanelSalvamentoLayout);
        jPanelSalvamentoLayout.setHorizontalGroup(
            jPanelSalvamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSalvamentoLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanelSalvamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSalvamentoLayout.createSequentialGroup()
                        .addComponent(jLabelListaSalvamento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonSair, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelSalvamentoLayout.createSequentialGroup()
                        .addComponent(jScrollPaneSalvamento, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonEditarSalvamento, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelSalvamentoLayout.createSequentialGroup()
                        .addGroup(jPanelSalvamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelSalvamentoLayout.createSequentialGroup()
                                .addComponent(jLabelPesquisaSalvamento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxPesquisaSalvamento, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelSalvamentoLayout.createSequentialGroup()
                                .addComponent(jTextFieldPesquisaSalvamento, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonPesquisaSalvamento, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelSalvamentoLayout.setVerticalGroup(
            jPanelSalvamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSalvamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSalvamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonSair, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelListaSalvamento))
                .addGap(24, 24, 24)
                .addGroup(jPanelSalvamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPesquisaSalvamento)
                    .addComponent(jComboBoxPesquisaSalvamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelSalvamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldPesquisaSalvamento)
                    .addComponent(jButtonPesquisaSalvamento, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelSalvamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPaneSalvamento, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEditarSalvamento, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );

        jPanelMenu.setBackground(new java.awt.Color(81, 81, 81));
        jPanelMenu.setForeground(new java.awt.Color(169, 203, 115));
        jPanelMenu.setPreferredSize(new java.awt.Dimension(180, 600));

        btnHome1.setBackground(new java.awt.Color(81, 81, 81));
        btnHome1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnHome1MousePressed(evt);
            }
        });

        jLabelBtnHome7.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabelBtnHome7.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBtnHome7.setText("Principal");

        javax.swing.GroupLayout btnHome1Layout = new javax.swing.GroupLayout(btnHome1);
        btnHome1.setLayout(btnHome1Layout);
        btnHome1Layout.setHorizontalGroup(
            btnHome1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnHome1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBtnHome7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
        );
        btnHome1Layout.setVerticalGroup(
            btnHome1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnHome1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBtnHome7, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnListaOcorrencia.setBackground(new java.awt.Color(81, 81, 81));
        btnListaOcorrencia.setPreferredSize(new java.awt.Dimension(180, 50));
        btnListaOcorrencia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnListaOcorrenciaMousePressed(evt);
            }
        });

        jLabelBtnListaOcorrencia.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabelBtnListaOcorrencia.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBtnListaOcorrencia.setText("Ocorrências");

        javax.swing.GroupLayout btnListaOcorrenciaLayout = new javax.swing.GroupLayout(btnListaOcorrencia);
        btnListaOcorrencia.setLayout(btnListaOcorrenciaLayout);
        btnListaOcorrenciaLayout.setHorizontalGroup(
            btnListaOcorrenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnListaOcorrenciaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBtnListaOcorrencia, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );
        btnListaOcorrenciaLayout.setVerticalGroup(
            btnListaOcorrenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnListaOcorrenciaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBtnListaOcorrencia, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnListaSalvamento.setBackground(new java.awt.Color(97, 97, 97));
        btnListaSalvamento.setPreferredSize(new java.awt.Dimension(180, 50));

        jLabelBtnListaSalvamento.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabelBtnListaSalvamento.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBtnListaSalvamento.setText("Salvamentos");

        javax.swing.GroupLayout btnListaSalvamentoLayout = new javax.swing.GroupLayout(btnListaSalvamento);
        btnListaSalvamento.setLayout(btnListaSalvamentoLayout);
        btnListaSalvamentoLayout.setHorizontalGroup(
            btnListaSalvamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnListaSalvamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBtnListaSalvamento, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );
        btnListaSalvamentoLayout.setVerticalGroup(
            btnListaSalvamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnListaSalvamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBtnListaSalvamento, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnListaAbrigo.setBackground(new java.awt.Color(81, 81, 81));
        btnListaAbrigo.setPreferredSize(new java.awt.Dimension(180, 50));
        btnListaAbrigo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnListaAbrigoMousePressed(evt);
            }
        });

        jLabelBtnListaAbrigo.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabelBtnListaAbrigo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBtnListaAbrigo.setText("Abrigos");

        javax.swing.GroupLayout btnListaAbrigoLayout = new javax.swing.GroupLayout(btnListaAbrigo);
        btnListaAbrigo.setLayout(btnListaAbrigoLayout);
        btnListaAbrigoLayout.setHorizontalGroup(
            btnListaAbrigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnListaAbrigoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBtnListaAbrigo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );
        btnListaAbrigoLayout.setVerticalGroup(
            btnListaAbrigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnListaAbrigoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBtnListaAbrigo, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnListaVeiculo.setBackground(new java.awt.Color(81, 81, 81));
        btnListaVeiculo.setPreferredSize(new java.awt.Dimension(180, 50));
        btnListaVeiculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnListaVeiculoMousePressed(evt);
            }
        });

        jLabelBtnListaVeiculo.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabelBtnListaVeiculo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBtnListaVeiculo.setText("Veiculos");

        javax.swing.GroupLayout btnListaVeiculoLayout = new javax.swing.GroupLayout(btnListaVeiculo);
        btnListaVeiculo.setLayout(btnListaVeiculoLayout);
        btnListaVeiculoLayout.setHorizontalGroup(
            btnListaVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnListaVeiculoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBtnListaVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );
        btnListaVeiculoLayout.setVerticalGroup(
            btnListaVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnListaVeiculoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBtnListaVeiculo, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnListaDadosGerais.setBackground(new java.awt.Color(81, 81, 81));
        btnListaDadosGerais.setPreferredSize(new java.awt.Dimension(180, 50));
        btnListaDadosGerais.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnListaDadosGeraisMousePressed(evt);
            }
        });

        jLabelBtnDadosGerais.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabelBtnDadosGerais.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBtnDadosGerais.setText("Dados Gerais");

        javax.swing.GroupLayout btnListaDadosGeraisLayout = new javax.swing.GroupLayout(btnListaDadosGerais);
        btnListaDadosGerais.setLayout(btnListaDadosGeraisLayout);
        btnListaDadosGeraisLayout.setHorizontalGroup(
            btnListaDadosGeraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnListaDadosGeraisLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBtnDadosGerais)
                .addContainerGap(67, Short.MAX_VALUE))
        );
        btnListaDadosGeraisLayout.setVerticalGroup(
            btnListaDadosGeraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnListaDadosGeraisLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBtnDadosGerais, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelHome.setForeground(new java.awt.Color(255, 255, 255));
        jPanelHome.setPreferredSize(new java.awt.Dimension(620, 600));
        jPanelHome.setRequestFocusEnabled(false);

        javax.swing.GroupLayout jPanelHomeLayout = new javax.swing.GroupLayout(jPanelHome);
        jPanelHome.setLayout(jPanelHomeLayout);
        jPanelHomeLayout.setHorizontalGroup(
            jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );
        jPanelHomeLayout.setVerticalGroup(
            jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 588, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelMenuLayout = new javax.swing.GroupLayout(jPanelMenu);
        jPanelMenu.setLayout(jPanelMenuLayout);
        jPanelMenuLayout.setHorizontalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuLayout.createSequentialGroup()
                .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMenuLayout.createSequentialGroup()
                        .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnListaOcorrencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnListaSalvamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnListaAbrigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnListaVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnListaDadosGerais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMenuLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnHome1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        jPanelMenuLayout.setVerticalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuLayout.createSequentialGroup()
                .addComponent(btnHome1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnListaOcorrencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnListaSalvamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnListaAbrigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnListaVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnListaDadosGerais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanelHome, 588, 588, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanelSalvamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelSalvamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

   
    private void jButtonEditarSalvamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarSalvamentoActionPerformed
        if (jTableSalvamento.getSelectedRow() > -1) {

            int id = Integer.parseInt(jTableSalvamento.getValueAt(jTableSalvamento.getSelectedRow(), 0).toString());
            Salvamento s = new SalvamentoDAO().buscarSalvamentoPorId(id);
            new JFrameCadastroSalvamento(s).setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Selecione algo para editar");
        }
    }//GEN-LAST:event_jButtonEditarSalvamentoActionPerformed

    private void jButtonPesquisaSalvamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisaSalvamentoActionPerformed
        String coluna = jComboBoxPesquisaSalvamento.getSelectedItem().toString();
        String valorPesquisar = jTextFieldPesquisaSalvamento.getText();
        popularListaSalvamentoPorPesquisa(coluna, valorPesquisar);
    }//GEN-LAST:event_jButtonPesquisaSalvamentoActionPerformed

    private void jComboBoxPesquisaSalvamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPesquisaSalvamentoActionPerformed
        //        String coluna = "";

    }//GEN-LAST:event_jComboBoxPesquisaSalvamentoActionPerformed

    private void jTextFieldPesquisaSalvamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPesquisaSalvamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPesquisaSalvamentoActionPerformed

    private void btnHome1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHome1MousePressed
        new JFrameTelaInicial().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnHome1MousePressed

    private void btnListaOcorrenciaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListaOcorrenciaMousePressed
        new JFrameListaOcorrencia().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnListaOcorrenciaMousePressed

    private void btnListaAbrigoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListaAbrigoMousePressed
        new JFrameListaAbrigo().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnListaAbrigoMousePressed

    private void btnListaVeiculoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListaVeiculoMousePressed
        new JFrameListaVeiculo().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnListaVeiculoMousePressed

    private void btnListaDadosGeraisMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListaDadosGeraisMousePressed
        new JFrameDadosGerais().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnListaDadosGeraisMousePressed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        popularListaSalvamento();
    }//GEN-LAST:event_formWindowActivated
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameListaSalvamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameListaSalvamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameListaSalvamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameListaSalvamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameListaSalvamento().setVisible(true);
            }
        });
    }
    
     public void popularListaSalvamentoPorPesquisa(String coluna, String valor) {
        DefaultTableModel modelo = (DefaultTableModel) jTableSalvamento.getModel();
        ArrayList<Salvamento> salvamentos = new SalvamentoDAO().pesquisarSalvamento(coluna, valor);
        modelo.setRowCount(0);
        for (Salvamento salvamento : salvamentos) {
            modelo.addRow(new Object[]{
                salvamento.getIdSalvamento(),
                salvamento.getFKOcorrencia().getIdOcorrencia(),
                Utilitarios.retornarPadraoBR(salvamento.getDataSalvamento()),
                salvamento.getHoraSalvamento(),
                salvamento.getLocalSalvamento(),
                salvamento.getJesusSalvador(),
                salvamento.getFKVeiculo().getPlacaVeiculo()
            });
        }
    }

    public void popularListaSalvamento (){
        DefaultTableModel modelo = (DefaultTableModel) jTableSalvamento.getModel();
        ArrayList<Salvamento> salvamentos = new SalvamentoDAO().retornarListaSalvamento();
        modelo.setRowCount(0);
        for (Salvamento salvamento : salvamentos) {
            modelo.addRow(new Object[]{
                salvamento.getIdSalvamento(),
                salvamento.getFKOcorrencia().getIdOcorrencia(),
                Utilitarios.retornarPadraoBR(salvamento.getDataSalvamento()),
                salvamento.getHoraSalvamento(),
                salvamento.getLocalSalvamento(),
                salvamento.getJesusSalvador(),
                salvamento.getFKVeiculo().getPlacaVeiculo()
            });
        }
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnHome1;
    private javax.swing.JPanel btnListaAbrigo;
    private javax.swing.JPanel btnListaDadosGerais;
    private javax.swing.JPanel btnListaOcorrencia;
    private javax.swing.JPanel btnListaSalvamento;
    private javax.swing.JPanel btnListaVeiculo;
    private javax.swing.JButton jButtonEditarSalvamento;
    private javax.swing.JButton jButtonPesquisaSalvamento;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JComboBox jComboBoxPesquisaSalvamento;
    private javax.swing.JLabel jLabelBtnDadosGerais;
    private javax.swing.JLabel jLabelBtnHome7;
    private javax.swing.JLabel jLabelBtnListaAbrigo;
    private javax.swing.JLabel jLabelBtnListaOcorrencia;
    private javax.swing.JLabel jLabelBtnListaSalvamento;
    private javax.swing.JLabel jLabelBtnListaVeiculo;
    private javax.swing.JLabel jLabelListaSalvamento;
    private javax.swing.JLabel jLabelPesquisaSalvamento;
    private javax.swing.JPanel jPanelHome;
    private javax.swing.JPanel jPanelMenu;
    private javax.swing.JPanel jPanelSalvamento;
    private javax.swing.JScrollPane jScrollPaneSalvamento;
    private javax.swing.JTable jTableSalvamento;
    private javax.swing.JTextField jTextFieldPesquisaSalvamento;
    // End of variables declaration//GEN-END:variables
}
