/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.TipoVeiculoDAO;
import database.Utilitarios;
import javax.swing.JOptionPane;
import model.TipoVeiculo;

/**
 *
 * @author Alunos
 */
public class JFrameCadastroTipoVeiculo extends javax.swing.JFrame {

    /**
     * Creates new form JFrameCadastroTipoVeiculo
     */
    public JFrameCadastroTipoVeiculo() {
        initComponents();
    }
    
    public JFrameCadastroTipoVeiculo(TipoVeiculo tv) {
        initComponents();
        jLabelIdTipoVeiculo.setText(String.valueOf(tv.getIdTipoVeiculo()));
        jTextFieldNomeTipoVeiculo.setText(tv.getNomeTipoVeiculo());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldNomeTipoVeiculo = new javax.swing.JTextField();
        jLabelIdTipoVeiculo = new javax.swing.JLabel();
        jLabelNomeTipoVeiculo = new javax.swing.JLabel();
        jButtonSalvarTipoVeiculo = new javax.swing.JButton();
        jLabelCadastroTipoVeiculo = new javax.swing.JLabel();
        jButtonCancelarOcorrencia = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTextFieldNomeTipoVeiculo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabelIdTipoVeiculo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelIdTipoVeiculo.setForeground(new java.awt.Color(81, 81, 81));
        jLabelIdTipoVeiculo.setText("Codigo");

        jLabelNomeTipoVeiculo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelNomeTipoVeiculo.setForeground(new java.awt.Color(81, 81, 81));
        jLabelNomeTipoVeiculo.setText("Nome");

        jButtonSalvarTipoVeiculo.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jButtonSalvarTipoVeiculo.setForeground(new java.awt.Color(81, 81, 81));
        jButtonSalvarTipoVeiculo.setText("Salvar");
        jButtonSalvarTipoVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarTipoVeiculoActionPerformed(evt);
            }
        });

        jLabelCadastroTipoVeiculo.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabelCadastroTipoVeiculo.setForeground(new java.awt.Color(81, 81, 81));
        jLabelCadastroTipoVeiculo.setText("CADASTRO TIPO DE VEÍCULO");

        jButtonCancelarOcorrencia.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jButtonCancelarOcorrencia.setForeground(new java.awt.Color(81, 81, 81));
        jButtonCancelarOcorrencia.setText("Cancelar");
        jButtonCancelarOcorrencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarOcorrenciaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCadastroTipoVeiculo)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelNomeTipoVeiculo)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldNomeTipoVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelIdTipoVeiculo))
                .addContainerGap(199, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonSalvarTipoVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCancelarOcorrencia, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabelCadastroTipoVeiculo)
                .addGap(42, 42, 42)
                .addComponent(jLabelIdTipoVeiculo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNomeTipoVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNomeTipoVeiculo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSalvarTipoVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCancelarOcorrencia, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalvarTipoVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarTipoVeiculoActionPerformed
        TipoVeiculo tv = new TipoVeiculo();
        tv.setNomeTipoVeiculo(jTextFieldNomeTipoVeiculo.getText());
        
        if (jLabelIdTipoVeiculo.getText().equals("")) {
            int codInserir = new TipoVeiculoDAO().inserir(tv);
            if (codInserir == Utilitarios.NAO_FOI_POSSIVEL_INSERIR) {
                JOptionPane.showMessageDialog(null, "Não foi Possível Inserir");
            }else {
                tv.setIdTipoVeiculo(codInserir);
                jLabelIdTipoVeiculo.setText(String.valueOf(codInserir));
                JOptionPane.showMessageDialog(null, "Tipo Veiculo Inserido com Sucesso");
            }
        }else {
            int id = Integer.parseInt(jLabelIdTipoVeiculo.getText());
            tv.setIdTipoVeiculo(id);
            int codAlteracao = new TipoVeiculoDAO().alterar(tv);
            if (codAlteracao == Utilitarios.NAO_FOI_POSSIVEL_ALTERAR) {
                JOptionPane.showMessageDialog(null, "Não foi Possível Alterar");
            }else {
                JOptionPane.showMessageDialog(null, "TipoVeiculo Alterado com Sucesso");
            }
        }
        dispose();
    }//GEN-LAST:event_jButtonSalvarTipoVeiculoActionPerformed

    private void jButtonCancelarOcorrenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarOcorrenciaActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonCancelarOcorrenciaActionPerformed

      
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameCadastroTipoVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameCadastroTipoVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameCadastroTipoVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameCadastroTipoVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameCadastroTipoVeiculo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelarOcorrencia;
    private javax.swing.JButton jButtonSalvarTipoVeiculo;
    private javax.swing.JLabel jLabelCadastroTipoVeiculo;
    private javax.swing.JLabel jLabelIdTipoVeiculo;
    private javax.swing.JLabel jLabelNomeTipoVeiculo;
    private javax.swing.JTextField jTextFieldNomeTipoVeiculo;
    // End of variables declaration//GEN-END:variables
}
