
package view;

import dao.VeiculoDAO;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import model.Veiculo;

/**
 *
 * @author Alunos  Talita vitoria, Felipe Tobias, Iara Oliveira e Vinicius donschen
 */
public class JFrameListaVeiculo extends javax.swing.JFrame {

    /**
     * Creates new form JFrameListaVeiculos
     */
    public JFrameListaVeiculo() {
        initComponents();
        popularListaVeiculos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelVeiculo = new javax.swing.JPanel();
        jButtonEditarVeiculo = new javax.swing.JButton();
        jButtonAdicionarVeiculo = new javax.swing.JButton();
        jTextFieldPesquisaVeiculo = new javax.swing.JTextField();
        jLabelPesquisaVeiculo = new javax.swing.JLabel();
        jButtonPesquisaVeiculo = new javax.swing.JButton();
        jScrollPaneVeiculo = new javax.swing.JScrollPane();
        jTableVeiculo = new javax.swing.JTable();
        jComboBoxPesquisaVeiculo = new javax.swing.JComboBox();
        jButtonSair = new javax.swing.JButton();
        jLabelListaVeiculos = new javax.swing.JLabel();
        jCheckBoxDisponivel = new javax.swing.JCheckBox();
        jPanelMenu = new javax.swing.JPanel();
        btnHome = new javax.swing.JPanel();
        jLabelBtnHome = new javax.swing.JLabel();
        btnListaOcorrencia = new javax.swing.JPanel();
        jLabelBtnListaOcorrencia = new javax.swing.JLabel();
        btnListaSalvamento = new javax.swing.JPanel();
        jLabelBtnListaSalvamento = new javax.swing.JLabel();
        btnListaAbrigo = new javax.swing.JPanel();
        jLabelBtnListaAbrigo = new javax.swing.JLabel();
        btnListaVeiculo = new javax.swing.JPanel();
        jLabelBtnListaVeiculo = new javax.swing.JLabel();
        btnListaDadosGerais = new javax.swing.JPanel();
        jLabelBtnDadosGerais = new javax.swing.JLabel();
        jPanelHome = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Veiculos");
        setBackground(new java.awt.Color(145, 145, 145));
        setBounds(new java.awt.Rectangle(700, 550, 0, 0));
        setLocationByPlatform(true);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanelVeiculo.setMaximumSize(new java.awt.Dimension(620, 600));
        jPanelVeiculo.setMinimumSize(new java.awt.Dimension(620, 600));
        jPanelVeiculo.setPreferredSize(new java.awt.Dimension(620, 600));

        jButtonEditarVeiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/edit-515151-64px.png"))); // NOI18N
        jButtonEditarVeiculo.setToolTipText("Editar veículo já existente");
        jButtonEditarVeiculo.setBorderPainted(false);
        jButtonEditarVeiculo.setContentAreaFilled(false);
        jButtonEditarVeiculo.setPreferredSize(new java.awt.Dimension(40, 40));
        jButtonEditarVeiculo.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/edit-a9cb73-64px.png"))); // NOI18N
        jButtonEditarVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarVeiculoActionPerformed(evt);
            }
        });

        jButtonAdicionarVeiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/add-515151-64px.png"))); // NOI18N
        jButtonAdicionarVeiculo.setToolTipText("Adicionar novo veículo");
        jButtonAdicionarVeiculo.setBorderPainted(false);
        jButtonAdicionarVeiculo.setContentAreaFilled(false);
        jButtonAdicionarVeiculo.setPreferredSize(new java.awt.Dimension(40, 40));
        jButtonAdicionarVeiculo.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/add-a9cb73-64px.png"))); // NOI18N
        jButtonAdicionarVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarVeiculoActionPerformed(evt);
            }
        });

        jTextFieldPesquisaVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPesquisaVeiculoActionPerformed(evt);
            }
        });

        jLabelPesquisaVeiculo.setText("Pesquisar por:");

        jButtonPesquisaVeiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/search-515151-32px.png"))); // NOI18N
        jButtonPesquisaVeiculo.setToolTipText("Pesquisar Veículo");
        jButtonPesquisaVeiculo.setBorderPainted(false);
        jButtonPesquisaVeiculo.setContentAreaFilled(false);
        jButtonPesquisaVeiculo.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/search-a9cb73-32px.png"))); // NOI18N
        jButtonPesquisaVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisaVeiculoActionPerformed(evt);
            }
        });

        jScrollPaneVeiculo.setMaximumSize(new java.awt.Dimension(500, 400));
        jScrollPaneVeiculo.setMinimumSize(new java.awt.Dimension(500, 400));
        jScrollPaneVeiculo.setPreferredSize(new java.awt.Dimension(500, 400));

        jTableVeiculo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Modelo", "Placa", "Fabricante", "Disponibilidade", "Tipo do Veiculo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableVeiculo.setColumnSelectionAllowed(true);
        jTableVeiculo.setGridColor(new java.awt.Color(81, 81, 81));
        jTableVeiculo.setIntercellSpacing(new java.awt.Dimension(1, 2));
        jTableVeiculo.setSelectionBackground(new java.awt.Color(169, 203, 115));
        jTableVeiculo.setShowVerticalLines(false);
        jTableVeiculo.getTableHeader().setResizingAllowed(false);
        jTableVeiculo.getTableHeader().setReorderingAllowed(false);
        jScrollPaneVeiculo.setViewportView(jTableVeiculo);
        jTableVeiculo.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (jTableVeiculo.getColumnModel().getColumnCount() > 0) {
            jTableVeiculo.getColumnModel().getColumn(0).setResizable(false);
            jTableVeiculo.getColumnModel().getColumn(1).setResizable(false);
            jTableVeiculo.getColumnModel().getColumn(2).setResizable(false);
            jTableVeiculo.getColumnModel().getColumn(3).setResizable(false);
            jTableVeiculo.getColumnModel().getColumn(4).setResizable(false);
            jTableVeiculo.getColumnModel().getColumn(5).setResizable(false);
        }

        jComboBoxPesquisaVeiculo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Código", "Modelo", "Placa", "Fabricante" }));
        jComboBoxPesquisaVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPesquisaVeiculoActionPerformed(evt);
            }
        });

        jButtonSair.setBackground(new java.awt.Color(81, 81, 81));
        jButtonSair.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jButtonSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/cancel-515151-64px.png"))); // NOI18N
        jButtonSair.setToolTipText("Sair");
        jButtonSair.setBorderPainted(false);
        jButtonSair.setContentAreaFilled(false);
        jButtonSair.setPreferredSize(new java.awt.Dimension(40, 40));
        jButtonSair.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/cancel-a9cb73-64px.png"))); // NOI18N
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        jLabelListaVeiculos.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabelListaVeiculos.setForeground(new java.awt.Color(81, 81, 81));
        jLabelListaVeiculos.setText("LISTA de VEÍCULOS");

        jCheckBoxDisponivel.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jCheckBoxDisponivel.setForeground(new java.awt.Color(81, 81, 81));
        jCheckBoxDisponivel.setSelected(true);
        jCheckBoxDisponivel.setText("Disponivel");

        javax.swing.GroupLayout jPanelVeiculoLayout = new javax.swing.GroupLayout(jPanelVeiculo);
        jPanelVeiculo.setLayout(jPanelVeiculoLayout);
        jPanelVeiculoLayout.setHorizontalGroup(
            jPanelVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVeiculoLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanelVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelVeiculoLayout.createSequentialGroup()
                        .addGroup(jPanelVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelVeiculoLayout.createSequentialGroup()
                                .addComponent(jLabelPesquisaVeiculo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxPesquisaVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBoxDisponivel))
                            .addComponent(jTextFieldPesquisaVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonPesquisaVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 191, Short.MAX_VALUE))
                    .addGroup(jPanelVeiculoLayout.createSequentialGroup()
                        .addGroup(jPanelVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelVeiculoLayout.createSequentialGroup()
                                .addComponent(jLabelListaVeiculos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonSair, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelVeiculoLayout.createSequentialGroup()
                                .addComponent(jScrollPaneVeiculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonAdicionarVeiculo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonEditarVeiculo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap())))
        );
        jPanelVeiculoLayout.setVerticalGroup(
            jPanelVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelVeiculoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonSair, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelListaVeiculos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(jPanelVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPesquisaVeiculo)
                    .addComponent(jComboBoxPesquisaVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxDisponivel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonPesquisaVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPesquisaVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelVeiculoLayout.createSequentialGroup()
                        .addComponent(jButtonAdicionarVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonEditarVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPaneVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );

        jPanelMenu.setBackground(new java.awt.Color(81, 81, 81));
        jPanelMenu.setForeground(new java.awt.Color(169, 203, 115));
        jPanelMenu.setPreferredSize(new java.awt.Dimension(180, 600));

        btnHome.setBackground(new java.awt.Color(81, 81, 81));
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnHomeMousePressed(evt);
            }
        });

        jLabelBtnHome.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabelBtnHome.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBtnHome.setText("Principal");

        javax.swing.GroupLayout btnHomeLayout = new javax.swing.GroupLayout(btnHome);
        btnHome.setLayout(btnHomeLayout);
        btnHomeLayout.setHorizontalGroup(
            btnHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBtnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
        );
        btnHomeLayout.setVerticalGroup(
            btnHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBtnHome, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnListaOcorrencia.setBackground(new java.awt.Color(81, 81, 81));
        btnListaOcorrencia.setPreferredSize(new java.awt.Dimension(180, 50));
        btnListaOcorrencia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnListaOcorrenciaMousePressed(evt);
            }
        });

        jLabelBtnListaOcorrencia.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabelBtnListaOcorrencia.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBtnListaOcorrencia.setText("Ocorrências");

        javax.swing.GroupLayout btnListaOcorrenciaLayout = new javax.swing.GroupLayout(btnListaOcorrencia);
        btnListaOcorrencia.setLayout(btnListaOcorrenciaLayout);
        btnListaOcorrenciaLayout.setHorizontalGroup(
            btnListaOcorrenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnListaOcorrenciaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBtnListaOcorrencia, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );
        btnListaOcorrenciaLayout.setVerticalGroup(
            btnListaOcorrenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnListaOcorrenciaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBtnListaOcorrencia, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnListaSalvamento.setBackground(new java.awt.Color(81, 81, 81));
        btnListaSalvamento.setPreferredSize(new java.awt.Dimension(180, 50));
        btnListaSalvamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnListaSalvamentoMousePressed(evt);
            }
        });

        jLabelBtnListaSalvamento.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabelBtnListaSalvamento.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBtnListaSalvamento.setText("Salvamentos");

        javax.swing.GroupLayout btnListaSalvamentoLayout = new javax.swing.GroupLayout(btnListaSalvamento);
        btnListaSalvamento.setLayout(btnListaSalvamentoLayout);
        btnListaSalvamentoLayout.setHorizontalGroup(
            btnListaSalvamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnListaSalvamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBtnListaSalvamento, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );
        btnListaSalvamentoLayout.setVerticalGroup(
            btnListaSalvamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnListaSalvamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBtnListaSalvamento, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnListaAbrigo.setBackground(new java.awt.Color(81, 81, 81));
        btnListaAbrigo.setPreferredSize(new java.awt.Dimension(180, 50));
        btnListaAbrigo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnListaAbrigoMousePressed(evt);
            }
        });

        jLabelBtnListaAbrigo.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabelBtnListaAbrigo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBtnListaAbrigo.setText("Abrigos");

        javax.swing.GroupLayout btnListaAbrigoLayout = new javax.swing.GroupLayout(btnListaAbrigo);
        btnListaAbrigo.setLayout(btnListaAbrigoLayout);
        btnListaAbrigoLayout.setHorizontalGroup(
            btnListaAbrigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnListaAbrigoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBtnListaAbrigo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );
        btnListaAbrigoLayout.setVerticalGroup(
            btnListaAbrigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnListaAbrigoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBtnListaAbrigo, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnListaVeiculo.setBackground(new java.awt.Color(97, 97, 97));
        btnListaVeiculo.setPreferredSize(new java.awt.Dimension(180, 50));

        jLabelBtnListaVeiculo.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabelBtnListaVeiculo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBtnListaVeiculo.setText("Veiculos");

        javax.swing.GroupLayout btnListaVeiculoLayout = new javax.swing.GroupLayout(btnListaVeiculo);
        btnListaVeiculo.setLayout(btnListaVeiculoLayout);
        btnListaVeiculoLayout.setHorizontalGroup(
            btnListaVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnListaVeiculoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBtnListaVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );
        btnListaVeiculoLayout.setVerticalGroup(
            btnListaVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnListaVeiculoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBtnListaVeiculo, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnListaDadosGerais.setBackground(new java.awt.Color(81, 81, 81));
        btnListaDadosGerais.setPreferredSize(new java.awt.Dimension(180, 50));
        btnListaDadosGerais.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnListaDadosGeraisMousePressed(evt);
            }
        });

        jLabelBtnDadosGerais.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabelBtnDadosGerais.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBtnDadosGerais.setText("Dados Gerais");

        javax.swing.GroupLayout btnListaDadosGeraisLayout = new javax.swing.GroupLayout(btnListaDadosGerais);
        btnListaDadosGerais.setLayout(btnListaDadosGeraisLayout);
        btnListaDadosGeraisLayout.setHorizontalGroup(
            btnListaDadosGeraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnListaDadosGeraisLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBtnDadosGerais)
                .addContainerGap(67, Short.MAX_VALUE))
        );
        btnListaDadosGeraisLayout.setVerticalGroup(
            btnListaDadosGeraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnListaDadosGeraisLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBtnDadosGerais, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelHome.setForeground(new java.awt.Color(255, 255, 255));
        jPanelHome.setPreferredSize(new java.awt.Dimension(620, 600));
        jPanelHome.setRequestFocusEnabled(false);

        javax.swing.GroupLayout jPanelHomeLayout = new javax.swing.GroupLayout(jPanelHome);
        jPanelHome.setLayout(jPanelHomeLayout);
        jPanelHomeLayout.setHorizontalGroup(
            jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );
        jPanelHomeLayout.setVerticalGroup(
            jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 588, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelMenuLayout = new javax.swing.GroupLayout(jPanelMenu);
        jPanelMenu.setLayout(jPanelMenuLayout);
        jPanelMenuLayout.setHorizontalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuLayout.createSequentialGroup()
                .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMenuLayout.createSequentialGroup()
                        .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnListaOcorrencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnListaSalvamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnListaAbrigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnListaVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnListaDadosGerais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMenuLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        jPanelMenuLayout.setVerticalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuLayout.createSequentialGroup()
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnListaOcorrencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnListaSalvamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnListaAbrigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnListaVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnListaDadosGerais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanelHome, 588, 588, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanelVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPesquisaVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisaVeiculoActionPerformed
       String coluna = jComboBoxPesquisaVeiculo.getSelectedItem().toString();
       String valorPesquisar = jTextFieldPesquisaVeiculo.getText();
       boolean disponibilidade = jCheckBoxDisponivel.isSelected();
       popularListaVeiculoPorPesquisa(coluna, valorPesquisar, disponibilidade);
    }//GEN-LAST:event_jButtonPesquisaVeiculoActionPerformed

    private void jButtonEditarVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarVeiculoActionPerformed
        if (jTableVeiculo.getSelectedRow() > -1) {
            int id = Integer.parseInt(jTableVeiculo.getValueAt(jTableVeiculo.getSelectedRow(), 0).toString());
            Veiculo veiculo = new VeiculoDAO().buscarVeiculoPorId(id);
            new JFrameCadastroVeiculo(veiculo).setVisible(true);
        }else {
            JOptionPane.showMessageDialog(null, "Selecione algo para editar");
        }
    }//GEN-LAST:event_jButtonEditarVeiculoActionPerformed

    private void jButtonAdicionarVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarVeiculoActionPerformed
        new JFrameCadastroVeiculo().setVisible(true);
    }//GEN-LAST:event_jButtonAdicionarVeiculoActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
       popularListaVeiculos();
    }//GEN-LAST:event_formWindowActivated

    private void jComboBoxPesquisaVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPesquisaVeiculoActionPerformed
        //        String coluna = "";

    }//GEN-LAST:event_jComboBoxPesquisaVeiculoActionPerformed

    private void jTextFieldPesquisaVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPesquisaVeiculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPesquisaVeiculoActionPerformed

    private void btnHomeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMousePressed
        new JFrameTelaInicial().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnHomeMousePressed

    private void btnListaOcorrenciaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListaOcorrenciaMousePressed
        new JFrameListaOcorrencia().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnListaOcorrenciaMousePressed

    private void btnListaSalvamentoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListaSalvamentoMousePressed
        new JFrameListaSalvamento().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnListaSalvamentoMousePressed

    private void btnListaAbrigoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListaAbrigoMousePressed
        new JFrameListaAbrigo().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnListaAbrigoMousePressed

    private void btnListaDadosGeraisMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListaDadosGeraisMousePressed
        new JFrameDadosGerais().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnListaDadosGeraisMousePressed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameListaVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameListaVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameListaVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameListaVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameListaVeiculo().setVisible(true);
            }
        });
    }
    
    public void popularListaVeiculoPorPesquisa(String coluna, String valor, boolean disponibilidade) {
        DefaultTableModel modelo = (DefaultTableModel) jTableVeiculo.getModel();
        ArrayList<Veiculo> veiculos = new VeiculoDAO().pesquisarVeiculo(coluna, valor, disponibilidade);
        modelo.setRowCount(0);
        for (Veiculo veiculo : veiculos) {
            modelo.addRow(new Object[]{
                veiculo.getIdVeiculo(),
                veiculo.getModeloVeiculo(),
                veiculo.getPlacaVeiculo(),
                veiculo.getFabricanteVeiculo(),
                veiculo.isEstaDisponivel(),
                veiculo.getFKTipoVeiculo().getNomeTipoVeiculo()
            });
        }
    }
    
    public void popularListaVeiculos() {
        DefaultTableModel modelo = (DefaultTableModel) jTableVeiculo.getModel();
        ArrayList<Veiculo> veiculos = new VeiculoDAO().retornarListaVeiculo();
        modelo.setRowCount(0);
        for(Veiculo veiculo : veiculos){
            modelo.addRow(new Object[]{
                veiculo.getIdVeiculo(),
                veiculo.getModeloVeiculo(), 
                veiculo.getPlacaVeiculo(), 
                veiculo.getFabricanteVeiculo(), 
                veiculo.isEstaDisponivel(), 
                veiculo.getFKTipoVeiculo().getNomeTipoVeiculo()
            });
        }
    }    
    
    public void clickDaTabela() {
        jTableVeiculo.getSelectionModel().addListSelectionListener(new ListSelectionListener() {

            @Override
            public void valueChanged(ListSelectionEvent e) {
                jButtonEditarVeiculo.setEnabled(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnHome;
    private javax.swing.JPanel btnListaAbrigo;
    private javax.swing.JPanel btnListaDadosGerais;
    private javax.swing.JPanel btnListaOcorrencia;
    private javax.swing.JPanel btnListaSalvamento;
    private javax.swing.JPanel btnListaVeiculo;
    private javax.swing.JButton jButtonAdicionarVeiculo;
    private javax.swing.JButton jButtonEditarVeiculo;
    private javax.swing.JButton jButtonPesquisaVeiculo;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JCheckBox jCheckBoxDisponivel;
    private javax.swing.JComboBox jComboBoxPesquisaVeiculo;
    private javax.swing.JLabel jLabelBtnDadosGerais;
    private javax.swing.JLabel jLabelBtnHome;
    private javax.swing.JLabel jLabelBtnListaAbrigo;
    private javax.swing.JLabel jLabelBtnListaOcorrencia;
    private javax.swing.JLabel jLabelBtnListaSalvamento;
    private javax.swing.JLabel jLabelBtnListaVeiculo;
    private javax.swing.JLabel jLabelListaVeiculos;
    private javax.swing.JLabel jLabelPesquisaVeiculo;
    private javax.swing.JPanel jPanelHome;
    private javax.swing.JPanel jPanelMenu;
    private javax.swing.JPanel jPanelVeiculo;
    private javax.swing.JScrollPane jScrollPaneVeiculo;
    private javax.swing.JTable jTableVeiculo;
    private javax.swing.JTextField jTextFieldPesquisaVeiculo;
    // End of variables declaration//GEN-END:variables
}
