package view;

import dao.TipoVeiculoDAO;
import dao.VeiculoDAO;
import database.Utilitarios;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import model.TipoVeiculo;
import model.Veiculo;

/**
 *
 * @author Alunos Talita vitoria, Felipe Tobias, Iara Oliveira e Vinicius
 * donschen
 */
public class JFrameCadastroVeiculo extends javax.swing.JFrame {

    /**
     * Creates new form JFrameCadastroVeiculo
     */
    public JFrameCadastroVeiculo() {
        initComponents();
        popularComponentes();
    }

    JFrameCadastroVeiculo(Veiculo veiculo) {
        initComponents();
        popularComponentes();
        jLabelNumId.setText(String.valueOf(veiculo.getIdVeiculo()));
        jTextFieldModeloVeiculo.setText(veiculo.getModeloVeiculo());
        jTextFieldPlacaVeiculo.setText(veiculo.getPlacaVeiculo());
        jComboBoxFabricanteVeiculo.setSelectedItem(veiculo.getFabricanteVeiculo());
        for (int i = 0; i < jComboBoxTipoVeiculo.getItemCount(); i++) {
            TipoVeiculo tipoVeiculo = jComboBoxTipoVeiculo.getItemAt(i);
            if (tipoVeiculo.getIdTipoVeiculo() == veiculo.getFKTipoVeiculo().getIdTipoVeiculo()) {
                jComboBoxTipoVeiculo.setSelectedIndex(i);
                return;
            }
        }
        if (veiculo.isEstaDisponivel()) {
            jRadioButtonVeiculoDisponivelSim.setSelected(true);
        } else {
            jRadioButtonVeiculoDisponivelNao.setSelected(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupVeiculoDIsponivel = new javax.swing.ButtonGroup();
        jLabelCadastroDeVeiculos = new javax.swing.JLabel();
        jLabelModeloVeiculo = new javax.swing.JLabel();
        jTextFieldModeloVeiculo = new javax.swing.JTextField();
        jLabelPlacaVeiculo = new javax.swing.JLabel();
        jTextFieldPlacaVeiculo = new javax.swing.JTextField();
        jComboBoxFabricanteVeiculo = new javax.swing.JComboBox();
        jLabelDisponivel = new javax.swing.JLabel();
        jRadioButtonVeiculoDisponivelNao = new javax.swing.JRadioButton();
        jButtonSalvarVeiculo = new javax.swing.JButton();
        jRadioButtonVeiculoDisponivelSim = new javax.swing.JRadioButton();
        jComboBoxTipoVeiculo = new javax.swing.JComboBox<TipoVeiculo>();
        jLabelFabricante = new javax.swing.JLabel();
        jLabelTipoVeiculo = new javax.swing.JLabel();
        jLabelCodigo = new javax.swing.JLabel();
        jLabelNumId = new javax.swing.JLabel();
        jButtonCancelarOcorrencia = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Veículos");

        jLabelCadastroDeVeiculos.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelCadastroDeVeiculos.setForeground(new java.awt.Color(81, 81, 81));
        jLabelCadastroDeVeiculos.setText("CADASTRO DE VEICULOS");

        jLabelModeloVeiculo.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabelModeloVeiculo.setForeground(new java.awt.Color(81, 81, 81));
        jLabelModeloVeiculo.setText("Modelo");

        jTextFieldModeloVeiculo.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jTextFieldModeloVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldModeloVeiculoActionPerformed(evt);
            }
        });

        jLabelPlacaVeiculo.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabelPlacaVeiculo.setForeground(new java.awt.Color(81, 81, 81));
        jLabelPlacaVeiculo.setText("Placa");

        jTextFieldPlacaVeiculo.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jTextFieldPlacaVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPlacaVeiculoActionPerformed(evt);
            }
        });

        jComboBoxFabricanteVeiculo.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jComboBoxFabricanteVeiculo.setForeground(new java.awt.Color(81, 81, 81));
        jComboBoxFabricanteVeiculo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ford", "Hyundai", "Honda", "Toyota", "Chevrolet", "VW" }));
        jComboBoxFabricanteVeiculo.setSelectedIndex(-1);

        jLabelDisponivel.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabelDisponivel.setForeground(new java.awt.Color(81, 81, 81));
        jLabelDisponivel.setText("Disponível");

        buttonGroupVeiculoDIsponivel.add(jRadioButtonVeiculoDisponivelNao);
        jRadioButtonVeiculoDisponivelNao.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jRadioButtonVeiculoDisponivelNao.setForeground(new java.awt.Color(81, 81, 81));
        jRadioButtonVeiculoDisponivelNao.setText("Não");

        jButtonSalvarVeiculo.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jButtonSalvarVeiculo.setForeground(new java.awt.Color(81, 81, 81));
        jButtonSalvarVeiculo.setText("Salvar");
        jButtonSalvarVeiculo.setToolTipText("");
        jButtonSalvarVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarVeiculoActionPerformed(evt);
            }
        });

        buttonGroupVeiculoDIsponivel.add(jRadioButtonVeiculoDisponivelSim);
        jRadioButtonVeiculoDisponivelSim.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jRadioButtonVeiculoDisponivelSim.setForeground(new java.awt.Color(81, 81, 81));
        jRadioButtonVeiculoDisponivelSim.setSelected(true);
        jRadioButtonVeiculoDisponivelSim.setText("Sim");

        jComboBoxTipoVeiculo.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jComboBoxTipoVeiculo.setForeground(new java.awt.Color(81, 81, 81));
        jComboBoxTipoVeiculo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        jComboBoxTipoVeiculo.setSelectedIndex(-1);
        jComboBoxTipoVeiculo.setToolTipText("");

        jLabelFabricante.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabelFabricante.setForeground(new java.awt.Color(81, 81, 81));
        jLabelFabricante.setText("Fabricante");

        jLabelTipoVeiculo.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabelTipoVeiculo.setForeground(new java.awt.Color(81, 81, 81));
        jLabelTipoVeiculo.setText("Tipo Veículo");

        jLabelCodigo.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabelCodigo.setForeground(new java.awt.Color(81, 81, 81));
        jLabelCodigo.setText("Código");

        jLabelNumId.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabelNumId.setForeground(new java.awt.Color(81, 81, 81));

        jButtonCancelarOcorrencia.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jButtonCancelarOcorrencia.setForeground(new java.awt.Color(81, 81, 81));
        jButtonCancelarOcorrencia.setText("Cancelar");
        jButtonCancelarOcorrencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarOcorrenciaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelModeloVeiculo)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextFieldModeloVeiculo)
                                .addComponent(jLabelPlacaVeiculo)
                                .addComponent(jTextFieldPlacaVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelCodigo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelNumId, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabelFabricante)
                                .addComponent(jLabelTipoVeiculo)
                                .addComponent(jComboBoxTipoVeiculo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboBoxFabricanteVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelDisponivel)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonVeiculoDisponivelSim)
                                .addGap(6, 6, 6)
                                .addComponent(jRadioButtonVeiculoDisponivelNao))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelCadastroDeVeiculos)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(97, 97, 97))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonSalvarVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCancelarOcorrencia, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabelCadastroDeVeiculos)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelCodigo)
                        .addComponent(jLabelDisponivel)
                        .addComponent(jRadioButtonVeiculoDisponivelSim)
                        .addComponent(jRadioButtonVeiculoDisponivelNao))
                    .addComponent(jLabelNumId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelModeloVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldModeloVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelPlacaVeiculo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldPlacaVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelFabricante)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxFabricanteVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelTipoVeiculo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxTipoVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(184, 184, 184)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSalvarVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCancelarOcorrencia, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldModeloVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldModeloVeiculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldModeloVeiculoActionPerformed

    private void jTextFieldPlacaVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPlacaVeiculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPlacaVeiculoActionPerformed

    private void jButtonSalvarVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarVeiculoActionPerformed
        if (jTextFieldModeloVeiculo.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "Modelo não pode ser vazio!");
            jTextFieldModeloVeiculo.requestFocus();
            return;
        }

        if (jTextFieldPlacaVeiculo.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "Placa não pode ser vazio!");
            return;
        }

        if (jComboBoxFabricanteVeiculo.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Fabricante não pode ser vazio!");
        }

        Veiculo v = new Veiculo();
        v.setModeloVeiculo(jTextFieldModeloVeiculo.getText());
        v.setPlacaVeiculo(jTextFieldPlacaVeiculo.getText());
        v.setFabricanteVeiculo(String.valueOf(jComboBoxFabricanteVeiculo.getSelectedItem()));
        v.setEstaDisponivel(jRadioButtonVeiculoDisponivelSim.isSelected());
        v.setFKTipoVeiculo((TipoVeiculo) jComboBoxTipoVeiculo.getSelectedItem());

        if (jLabelNumId.getText().equals("")) {
            int codInserir = new VeiculoDAO().inserir(v);
            if (codInserir == Utilitarios.NAO_FOI_POSSIVEL_INSERIR) {
                JOptionPane.showMessageDialog(null, "Não foi Possível Inserir");
            } else {
                v.setIdVeiculo(codInserir);
                jLabelNumId.setText(String.valueOf(codInserir));
                JOptionPane.showMessageDialog(null, "Veículo Inserido com Sucesso");
            }
        } else {
            int id = Integer.parseInt(jLabelNumId.getText());
            v.setIdVeiculo(id);
            int codAlteracao = new VeiculoDAO().alterar(v);
            if (codAlteracao == Utilitarios.NAO_FOI_POSSIVEL_ALTERAR) {
                JOptionPane.showMessageDialog(null, "Não foi Possível Alterar");
            } else {
                JOptionPane.showMessageDialog(null, "Veículo Alterado com Sucesso");
            }
        }
        dispose();
    }//GEN-LAST:event_jButtonSalvarVeiculoActionPerformed

    private void jButtonCancelarOcorrenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarOcorrenciaActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonCancelarOcorrenciaActionPerformed

    private void popularComponentes() {
        ArrayList<TipoVeiculo> tipoVeiculos = new TipoVeiculoDAO().retornarListaTipoVeiculo();
        jComboBoxTipoVeiculo.removeAllItems();
        for (TipoVeiculo tipoVeiculo : tipoVeiculos) {

            jComboBoxTipoVeiculo.addItem(tipoVeiculo);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameCadastroVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameCadastroVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameCadastroVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameCadastroVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameCadastroVeiculo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupVeiculoDIsponivel;
    private javax.swing.JButton jButtonCancelarOcorrencia;
    private javax.swing.JButton jButtonSalvarVeiculo;
    private javax.swing.JComboBox jComboBoxFabricanteVeiculo;
    private javax.swing.JComboBox<TipoVeiculo> jComboBoxTipoVeiculo;
    private javax.swing.JLabel jLabelCadastroDeVeiculos;
    private javax.swing.JLabel jLabelCodigo;
    private javax.swing.JLabel jLabelDisponivel;
    private javax.swing.JLabel jLabelFabricante;
    private javax.swing.JLabel jLabelModeloVeiculo;
    private javax.swing.JLabel jLabelNumId;
    private javax.swing.JLabel jLabelPlacaVeiculo;
    private javax.swing.JLabel jLabelTipoVeiculo;
    private javax.swing.JRadioButton jRadioButtonVeiculoDisponivelNao;
    private javax.swing.JRadioButton jRadioButtonVeiculoDisponivelSim;
    private javax.swing.JTextField jTextFieldModeloVeiculo;
    private javax.swing.JTextField jTextFieldPlacaVeiculo;
    // End of variables declaration//GEN-END:variables
}
