/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.OcorrenciaDAO;
import database.Utilitarios;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.Ocorrencia;
import model.Salvamento;

/**
 *
 * @author Alunos
 */
public class JFrameTelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form JFrameTelaInicial
     */
    public JFrameTelaInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMenu = new javax.swing.JPanel();
        btnHome = new javax.swing.JPanel();
        jLabelBtnHome = new javax.swing.JLabel();
        btnListaOcorrencia = new javax.swing.JPanel();
        jLabelBtnListaOcorrencia = new javax.swing.JLabel();
        btnListaSalvamento = new javax.swing.JPanel();
        jLabelBtnListaSalvamento = new javax.swing.JLabel();
        btnListaAbrigo = new javax.swing.JPanel();
        jLabelBtnListaAbrigo = new javax.swing.JLabel();
        btnListaVeiculo = new javax.swing.JPanel();
        jLabelBtnListaVeiculo = new javax.swing.JLabel();
        btnListaDadosGerais = new javax.swing.JPanel();
        jLabelBtnDadosGerais = new javax.swing.JLabel();
        jPanelHome = new javax.swing.JPanel();
        jButtonSair = new javax.swing.JButton();
        jLabelImagem = new javax.swing.JLabel();
        jLabelBemVindo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        setResizable(false);

        jPanelMenu.setBackground(new java.awt.Color(81, 81, 81));
        jPanelMenu.setForeground(new java.awt.Color(169, 203, 115));
        jPanelMenu.setPreferredSize(new java.awt.Dimension(180, 600));

        btnHome.setBackground(new java.awt.Color(97, 97, 97));
        btnHome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabelBtnHome.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabelBtnHome.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBtnHome.setText("Principal");

        javax.swing.GroupLayout btnHomeLayout = new javax.swing.GroupLayout(btnHome);
        btnHome.setLayout(btnHomeLayout);
        btnHomeLayout.setHorizontalGroup(
            btnHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBtnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
        );
        btnHomeLayout.setVerticalGroup(
            btnHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBtnHome, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnListaOcorrencia.setBackground(new java.awt.Color(81, 81, 81));
        btnListaOcorrencia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnListaOcorrencia.setPreferredSize(new java.awt.Dimension(180, 50));
        btnListaOcorrencia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnListaOcorrenciaMousePressed(evt);
            }
        });

        jLabelBtnListaOcorrencia.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabelBtnListaOcorrencia.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBtnListaOcorrencia.setText("Ocorrências");

        javax.swing.GroupLayout btnListaOcorrenciaLayout = new javax.swing.GroupLayout(btnListaOcorrencia);
        btnListaOcorrencia.setLayout(btnListaOcorrenciaLayout);
        btnListaOcorrenciaLayout.setHorizontalGroup(
            btnListaOcorrenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnListaOcorrenciaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBtnListaOcorrencia, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );
        btnListaOcorrenciaLayout.setVerticalGroup(
            btnListaOcorrenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnListaOcorrenciaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBtnListaOcorrencia, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnListaSalvamento.setBackground(new java.awt.Color(81, 81, 81));
        btnListaSalvamento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnListaSalvamento.setPreferredSize(new java.awt.Dimension(180, 50));
        btnListaSalvamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnListaSalvamentoMousePressed(evt);
            }
        });

        jLabelBtnListaSalvamento.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabelBtnListaSalvamento.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBtnListaSalvamento.setText("Salvamentos");

        javax.swing.GroupLayout btnListaSalvamentoLayout = new javax.swing.GroupLayout(btnListaSalvamento);
        btnListaSalvamento.setLayout(btnListaSalvamentoLayout);
        btnListaSalvamentoLayout.setHorizontalGroup(
            btnListaSalvamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnListaSalvamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBtnListaSalvamento, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );
        btnListaSalvamentoLayout.setVerticalGroup(
            btnListaSalvamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnListaSalvamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBtnListaSalvamento, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnListaAbrigo.setBackground(new java.awt.Color(81, 81, 81));
        btnListaAbrigo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnListaAbrigo.setPreferredSize(new java.awt.Dimension(180, 50));
        btnListaAbrigo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnListaAbrigoMousePressed(evt);
            }
        });

        jLabelBtnListaAbrigo.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabelBtnListaAbrigo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBtnListaAbrigo.setText("Abrigos");

        javax.swing.GroupLayout btnListaAbrigoLayout = new javax.swing.GroupLayout(btnListaAbrigo);
        btnListaAbrigo.setLayout(btnListaAbrigoLayout);
        btnListaAbrigoLayout.setHorizontalGroup(
            btnListaAbrigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnListaAbrigoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBtnListaAbrigo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );
        btnListaAbrigoLayout.setVerticalGroup(
            btnListaAbrigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnListaAbrigoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBtnListaAbrigo, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnListaVeiculo.setBackground(new java.awt.Color(81, 81, 81));
        btnListaVeiculo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnListaVeiculo.setPreferredSize(new java.awt.Dimension(180, 50));
        btnListaVeiculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnListaVeiculoMousePressed(evt);
            }
        });

        jLabelBtnListaVeiculo.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabelBtnListaVeiculo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBtnListaVeiculo.setText("Veiculos");

        javax.swing.GroupLayout btnListaVeiculoLayout = new javax.swing.GroupLayout(btnListaVeiculo);
        btnListaVeiculo.setLayout(btnListaVeiculoLayout);
        btnListaVeiculoLayout.setHorizontalGroup(
            btnListaVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnListaVeiculoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBtnListaVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );
        btnListaVeiculoLayout.setVerticalGroup(
            btnListaVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnListaVeiculoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBtnListaVeiculo, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnListaDadosGerais.setBackground(new java.awt.Color(81, 81, 81));
        btnListaDadosGerais.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnListaDadosGerais.setPreferredSize(new java.awt.Dimension(180, 50));
        btnListaDadosGerais.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnListaDadosGeraisMousePressed(evt);
            }
        });

        jLabelBtnDadosGerais.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabelBtnDadosGerais.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBtnDadosGerais.setText("Dados Gerais");

        javax.swing.GroupLayout btnListaDadosGeraisLayout = new javax.swing.GroupLayout(btnListaDadosGerais);
        btnListaDadosGerais.setLayout(btnListaDadosGeraisLayout);
        btnListaDadosGeraisLayout.setHorizontalGroup(
            btnListaDadosGeraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnListaDadosGeraisLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBtnDadosGerais)
                .addContainerGap(67, Short.MAX_VALUE))
        );
        btnListaDadosGeraisLayout.setVerticalGroup(
            btnListaDadosGeraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnListaDadosGeraisLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBtnDadosGerais, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelHome.setForeground(new java.awt.Color(255, 255, 255));
        jPanelHome.setPreferredSize(new java.awt.Dimension(620, 600));
        jPanelHome.setRequestFocusEnabled(false);

        javax.swing.GroupLayout jPanelHomeLayout = new javax.swing.GroupLayout(jPanelHome);
        jPanelHome.setLayout(jPanelHomeLayout);
        jPanelHomeLayout.setHorizontalGroup(
            jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );
        jPanelHomeLayout.setVerticalGroup(
            jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 598, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelMenuLayout = new javax.swing.GroupLayout(jPanelMenu);
        jPanelMenu.setLayout(jPanelMenuLayout);
        jPanelMenuLayout.setHorizontalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuLayout.createSequentialGroup()
                .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMenuLayout.createSequentialGroup()
                        .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnListaOcorrencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnListaSalvamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnListaAbrigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnListaVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnListaDadosGerais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMenuLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        jPanelMenuLayout.setVerticalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuLayout.createSequentialGroup()
                .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMenuLayout.createSequentialGroup()
                        .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnListaOcorrencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnListaSalvamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnListaAbrigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnListaVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnListaDadosGerais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanelHome, 598, 598, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 2, Short.MAX_VALUE))
        );

        jButtonSair.setBackground(new java.awt.Color(81, 81, 81));
        jButtonSair.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jButtonSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/cancel-515151-64px.png"))); // NOI18N
        jButtonSair.setToolTipText("Sair");
        jButtonSair.setBorderPainted(false);
        jButtonSair.setContentAreaFilled(false);
        jButtonSair.setPreferredSize(new java.awt.Dimension(40, 40));
        jButtonSair.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/cancel-a9cb73-64px.png"))); // NOI18N
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        jLabelImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/logo-515151-256px.png"))); // NOI18N
        jLabelImagem.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabelImagemMouseMoved(evt);
            }
        });

        jLabelBemVindo.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabelBemVindo.setForeground(new java.awt.Color(81, 81, 81));
        jLabelBemVindo.setText("Bem-Vindo ao Consciência Animal");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonSair, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelBemVindo)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58)))
                        .addGap(110, 110, 110))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonSair, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabelImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jLabelBemVindo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnListaSalvamentoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListaSalvamentoMousePressed
        new JFrameListaSalvamento().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnListaSalvamentoMousePressed

    private void btnListaAbrigoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListaAbrigoMousePressed
        new JFrameListaAbrigo().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnListaAbrigoMousePressed

    private void btnListaVeiculoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListaVeiculoMousePressed
        new JFrameListaVeiculo().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnListaVeiculoMousePressed

    private void btnListaDadosGeraisMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListaDadosGeraisMousePressed
        new JFrameDadosGerais().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnListaDadosGeraisMousePressed

    private void btnListaOcorrenciaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListaOcorrenciaMousePressed
        new JFrameListaOcorrencia().setVisible(true);
        dispose();
        
        
    }//GEN-LAST:event_btnListaOcorrenciaMousePressed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
      System.exit(0);
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jLabelImagemMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelImagemMouseMoved
        //      jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/logo-color-256")));
    }//GEN-LAST:event_jLabelImagemMouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameTelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameTelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameTelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameTelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameTelaInicial().setVisible(true);
            }
        });
    }
    
  
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnHome;
    private javax.swing.JPanel btnListaAbrigo;
    private javax.swing.JPanel btnListaDadosGerais;
    private javax.swing.JPanel btnListaOcorrencia;
    private javax.swing.JPanel btnListaSalvamento;
    private javax.swing.JPanel btnListaVeiculo;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JLabel jLabelBemVindo;
    private javax.swing.JLabel jLabelBtnDadosGerais;
    private javax.swing.JLabel jLabelBtnHome;
    private javax.swing.JLabel jLabelBtnListaAbrigo;
    private javax.swing.JLabel jLabelBtnListaOcorrencia;
    private javax.swing.JLabel jLabelBtnListaSalvamento;
    private javax.swing.JLabel jLabelBtnListaVeiculo;
    private javax.swing.JLabel jLabelImagem;
    private javax.swing.JPanel jPanelHome;
    private javax.swing.JPanel jPanelMenu;
    // End of variables declaration//GEN-END:variables
}
