/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.OcorrenciaDAO;
import database.Utilitarios;
import javax.swing.JOptionPane;
import model.Ocorrencia;

/**
 *
 * @author scraw
 */
public class JFrameCadastroOcorrencia extends javax.swing.JFrame {

    /**
     * Creates new form JFrameCadastroOcorrencia
     */
    public JFrameCadastroOcorrencia() {
        initComponents();
    }

    JFrameCadastroOcorrencia(Ocorrencia o) {
        initComponents();
        jLabelIdOcorrencia.setText(String.valueOf(o.getIdOcorrencia()));
        jTextFieldHoraOcorrencia.setText(o.getHoraOcorrencia());
        jTextFieldDataOcorrencia.setText(Utilitarios.retornarPadraoBR(o.getDataOcorrencia()));
        jTextFieldLocalOcorrencia.setText(o.getLocalOcorrencia());
        jTextAreaDescricaoOcorrencia.setText(o.getDescricaoOcorrencia());
        
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldDataOcorrencia = new javax.swing.JTextField();
        jTextFieldHoraOcorrencia = new javax.swing.JTextField();
        jTextFieldLocalOcorrencia = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDescricaoOcorrencia = new javax.swing.JTextArea();
        jLabelDataOcorrencia = new javax.swing.JLabel();
        jLabelHoraOcorrencia = new javax.swing.JLabel();
        jLabelLocalOcorrencia = new javax.swing.JLabel();
        jLabelDescricaoOcorrencia = new javax.swing.JLabel();
        jButtoSalvar = new javax.swing.JButton();
        jButtonCancelarOcorrencia = new javax.swing.JButton();
        jLabelIdOcorrencia = new javax.swing.JLabel();
        jLabelCadastroOcorrecia = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jTextFieldDataOcorrencia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldDataOcorrencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDataOcorrenciaActionPerformed(evt);
            }
        });

        jTextFieldHoraOcorrencia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTextFieldLocalOcorrencia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jScrollPane1.setForeground(new java.awt.Color(81, 81, 81));

        jTextAreaDescricaoOcorrencia.setColumns(20);
        jTextAreaDescricaoOcorrencia.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jTextAreaDescricaoOcorrencia.setRows(5);
        jScrollPane1.setViewportView(jTextAreaDescricaoOcorrencia);

        jLabelDataOcorrencia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelDataOcorrencia.setForeground(new java.awt.Color(81, 81, 81));
        jLabelDataOcorrencia.setText("Data");

        jLabelHoraOcorrencia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelHoraOcorrencia.setForeground(new java.awt.Color(81, 81, 81));
        jLabelHoraOcorrencia.setText("Hora");

        jLabelLocalOcorrencia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelLocalOcorrencia.setForeground(new java.awt.Color(81, 81, 81));
        jLabelLocalOcorrencia.setText("Local");

        jLabelDescricaoOcorrencia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelDescricaoOcorrencia.setForeground(new java.awt.Color(81, 81, 81));
        jLabelDescricaoOcorrencia.setText("Descrição");

        jButtoSalvar.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jButtoSalvar.setForeground(new java.awt.Color(81, 81, 81));
        jButtoSalvar.setText("Salvar");
        jButtoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoSalvarActionPerformed(evt);
            }
        });

        jButtonCancelarOcorrencia.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jButtonCancelarOcorrencia.setForeground(new java.awt.Color(81, 81, 81));
        jButtonCancelarOcorrencia.setText("Cancelar");
        jButtonCancelarOcorrencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarOcorrenciaActionPerformed(evt);
            }
        });

        jLabelIdOcorrencia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelIdOcorrencia.setForeground(new java.awt.Color(81, 81, 81));

        jLabelCadastroOcorrecia.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabelCadastroOcorrecia.setForeground(new java.awt.Color(81, 81, 81));
        jLabelCadastroOcorrecia.setText("CADASTRO de OCORRÊNCIA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelDataOcorrencia)
                                    .addComponent(jLabelIdOcorrencia, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldDataOcorrencia, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabelLocalOcorrencia)
                                    .addComponent(jLabelHoraOcorrencia)
                                    .addComponent(jTextFieldLocalOcorrencia)
                                    .addComponent(jTextFieldHoraOcorrencia, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelCadastroOcorrecia)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelDescricaoOcorrencia)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jButtoSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButtonCancelarOcorrencia, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabelCadastroOcorrecia)
                .addGap(18, 18, 18)
                .addComponent(jLabelHoraOcorrencia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldHoraOcorrencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jLabelLocalOcorrencia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldLocalOcorrencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelIdOcorrencia, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelDataOcorrencia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldDataOcorrencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36)
                .addComponent(jLabelDescricaoOcorrencia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtoSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCancelarOcorrencia, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        jTextFieldDataOcorrencia.getAccessibleContext().setAccessibleName("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldDataOcorrenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDataOcorrenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDataOcorrenciaActionPerformed

    private void jButtoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoSalvarActionPerformed
        if(jTextFieldDataOcorrencia.getText().length() == 0){
            JOptionPane.showMessageDialog(null, "Data não pode ser vazio!!");
            jTextFieldDataOcorrencia.requestFocus();
            return;
        }
        
        if(jTextFieldHoraOcorrencia.getText().length() == 0){
            JOptionPane.showMessageDialog(null, "Hora não pode ser vazio!!");
            jTextFieldHoraOcorrencia.requestFocus();
            return;
        }
        
        if(jTextFieldLocalOcorrencia.getText().length() == 0){
            JOptionPane.showMessageDialog(null, "Local não pode ser vazio!!");
            jTextFieldLocalOcorrencia.requestFocus();
            return;
        }
        
        if(jTextAreaDescricaoOcorrencia.getText().length() == 0){
            JOptionPane.showMessageDialog(null, "Descrição não pode ser vazio!!");
            jTextAreaDescricaoOcorrencia.requestFocus();
            return;
        }
        
        Ocorrencia o = new Ocorrencia();
        
        o.setDataOcorrencia(Utilitarios.retorarPadraoUS(jTextFieldDataOcorrencia.getText()));
        o.setHoraOcorrencia(jTextFieldHoraOcorrencia.getText());
        o.setLocalOcorrencia(jTextFieldLocalOcorrencia.getText());
        o.setDescricaoOcorrencia(jTextAreaDescricaoOcorrencia.getText());
        
        if (jLabelIdOcorrencia.getText().equals("")) {
            int codInserir = new OcorrenciaDAO().inserir(o);
            if (codInserir == Utilitarios.NAO_FOI_POSSIVEL_INSERIR) {
                JOptionPane.showMessageDialog(null, "Não foi Possível Inserir");
            }else {
                o.setIdOcorrencia(codInserir);
                jLabelIdOcorrencia.setText(String.valueOf(codInserir));
                JOptionPane.showMessageDialog(null, "Ocorrencia Inserida com Sucesso");
            }
        }else {
            int id = Integer.parseInt(jLabelIdOcorrencia.getText());
            o.setIdOcorrencia(id);
            int codAlteracao = new OcorrenciaDAO().alterar(o);
            if (codAlteracao == Utilitarios.NAO_FOI_POSSIVEL_ALTERAR) {
                JOptionPane.showMessageDialog(null, "Não foi Possível Alterar");
            }else {
                JOptionPane.showMessageDialog(null, "Ocorrencia Alterada com Sucesso");
            }
            
        
        }
        dispose();
    }//GEN-LAST:event_jButtoSalvarActionPerformed

    private void jButtonCancelarOcorrenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarOcorrenciaActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonCancelarOcorrenciaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameCadastroOcorrencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameCadastroOcorrencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameCadastroOcorrencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameCadastroOcorrencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameCadastroOcorrencia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtoSalvar;
    private javax.swing.JButton jButtonCancelarOcorrencia;
    private javax.swing.JLabel jLabelCadastroOcorrecia;
    private javax.swing.JLabel jLabelDataOcorrencia;
    private javax.swing.JLabel jLabelDescricaoOcorrencia;
    private javax.swing.JLabel jLabelHoraOcorrencia;
    private javax.swing.JLabel jLabelIdOcorrencia;
    private javax.swing.JLabel jLabelLocalOcorrencia;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaDescricaoOcorrencia;
    private javax.swing.JTextField jTextFieldDataOcorrencia;
    private javax.swing.JTextField jTextFieldHoraOcorrencia;
    private javax.swing.JTextField jTextFieldLocalOcorrencia;
    // End of variables declaration//GEN-END:variables
}
