/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.TipoVeiculoDAO;
import database.Utilitarios;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.TipoVeiculo;

/**
 *
 * @author Alunos
 */
public class JFrameListaTipoVeiculo extends javax.swing.JFrame {

    /**
     * Creates new form JFrameListaTipoVeiculo
     */
    public JFrameListaTipoVeiculo() {
        initComponents();
        popularListaTipoVeiculo();
    }
    
           
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTipoVeiculo = new javax.swing.JPanel();
        jComboBoxPesquisaTipoVeiculo = new javax.swing.JComboBox();
        jButtonEditarTipoVeiculo = new javax.swing.JButton();
        jButtonAdicionarTipoVeiculo = new javax.swing.JButton();
        jTextFieldPesquisaTipoVeiculo = new javax.swing.JTextField();
        jButtonPesquisaTipoVeiculo = new javax.swing.JButton();
        jScrollPaneTipoVeiculo = new javax.swing.JScrollPane();
        jTableTipoVeiculo = new javax.swing.JTable();
        jLabelPesquisaTipoVeiculo = new javax.swing.JLabel();
        jButtonExcluirTipoVeiculo = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jPanelMenu = new javax.swing.JPanel();
        btnHome = new javax.swing.JPanel();
        jLabelBtnHome = new javax.swing.JLabel();
        btnListaOcorrencia = new javax.swing.JPanel();
        jLabelBtnListaOcorrencia = new javax.swing.JLabel();
        btnListaSalvamento = new javax.swing.JPanel();
        jLabelBtnListaSalvamento = new javax.swing.JLabel();
        btnListaAbrigo = new javax.swing.JPanel();
        jLabelBtnListaAbrigo = new javax.swing.JLabel();
        btnListaVeiculo = new javax.swing.JPanel();
        jLabelBtnListaVeiculo = new javax.swing.JLabel();
        btnListaDadosGerais = new javax.swing.JPanel();
        jLabelBtnDadosGerais = new javax.swing.JLabel();
        jPanelHome = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tipos de Veículo");
        setBounds(new java.awt.Rectangle(800, 600, 0, 0));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setUndecorated(true);
        setResizable(false);

        jPanelTipoVeiculo.setPreferredSize(new java.awt.Dimension(620, 600));

        jComboBoxPesquisaTipoVeiculo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Código", "Tipo Veículo" }));
        jComboBoxPesquisaTipoVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPesquisaTipoVeiculoActionPerformed(evt);
            }
        });

        jButtonEditarTipoVeiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/edit-515151-64px.png"))); // NOI18N
        jButtonEditarTipoVeiculo.setBorderPainted(false);
        jButtonEditarTipoVeiculo.setContentAreaFilled(false);
        jButtonEditarTipoVeiculo.setPreferredSize(new java.awt.Dimension(40, 40));
        jButtonEditarTipoVeiculo.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/edit-a9cb73-64px.png"))); // NOI18N
        jButtonEditarTipoVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarTipoVeiculoActionPerformed(evt);
            }
        });

        jButtonAdicionarTipoVeiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/add-515151-64px.png"))); // NOI18N
        jButtonAdicionarTipoVeiculo.setBorderPainted(false);
        jButtonAdicionarTipoVeiculo.setContentAreaFilled(false);
        jButtonAdicionarTipoVeiculo.setPreferredSize(new java.awt.Dimension(40, 40));
        jButtonAdicionarTipoVeiculo.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/add-a9cb73-64px.png"))); // NOI18N
        jButtonAdicionarTipoVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarTipoVeiculoActionPerformed(evt);
            }
        });

        jTextFieldPesquisaTipoVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPesquisaTipoVeiculoActionPerformed(evt);
            }
        });

        jButtonPesquisaTipoVeiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/search-515151-32px.png"))); // NOI18N
        jButtonPesquisaTipoVeiculo.setBorderPainted(false);
        jButtonPesquisaTipoVeiculo.setContentAreaFilled(false);
        jButtonPesquisaTipoVeiculo.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/search-a9cb73-32px.png"))); // NOI18N
        jButtonPesquisaTipoVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisaTipoVeiculoActionPerformed(evt);
            }
        });

        jTableTipoVeiculo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Id", "Tipo do Veículo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableTipoVeiculo.setGridColor(new java.awt.Color(81, 81, 81));
        jTableTipoVeiculo.setIntercellSpacing(new java.awt.Dimension(1, 2));
        jTableTipoVeiculo.setMaximumSize(new java.awt.Dimension(500, 400));
        jTableTipoVeiculo.setMinimumSize(new java.awt.Dimension(500, 400));
        jTableTipoVeiculo.setPreferredSize(new java.awt.Dimension(500, 400));
        jTableTipoVeiculo.setSelectionBackground(new java.awt.Color(169, 203, 115));
        jTableTipoVeiculo.setShowVerticalLines(false);
        jTableTipoVeiculo.getTableHeader().setResizingAllowed(false);
        jTableTipoVeiculo.getTableHeader().setReorderingAllowed(false);
        jScrollPaneTipoVeiculo.setViewportView(jTableTipoVeiculo);
        jTableTipoVeiculo.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (jTableTipoVeiculo.getColumnModel().getColumnCount() > 0) {
            jTableTipoVeiculo.getColumnModel().getColumn(0).setResizable(false);
            jTableTipoVeiculo.getColumnModel().getColumn(1).setResizable(false);
        }
        jTableTipoVeiculo.getAccessibleContext().setAccessibleName("");

        jLabelPesquisaTipoVeiculo.setText("Pesquisar por:");

        jButtonExcluirTipoVeiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/trash-515151-64px.png"))); // NOI18N
        jButtonExcluirTipoVeiculo.setBorderPainted(false);
        jButtonExcluirTipoVeiculo.setContentAreaFilled(false);
        jButtonExcluirTipoVeiculo.setPreferredSize(new java.awt.Dimension(40, 40));
        jButtonExcluirTipoVeiculo.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/trash-a9cb73-64px.png"))); // NOI18N
        jButtonExcluirTipoVeiculo.setSelected(true);
        jButtonExcluirTipoVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirTipoVeiculoActionPerformed(evt);
            }
        });

        jButtonSair.setBackground(new java.awt.Color(81, 81, 81));
        jButtonSair.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jButtonSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/cancel-515151-64px.png"))); // NOI18N
        jButtonSair.setToolTipText("Sair");
        jButtonSair.setBorderPainted(false);
        jButtonSair.setContentAreaFilled(false);
        jButtonSair.setPreferredSize(new java.awt.Dimension(40, 40));
        jButtonSair.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/cancel-a9cb73-64px.png"))); // NOI18N
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelTipoVeiculoLayout = new javax.swing.GroupLayout(jPanelTipoVeiculo);
        jPanelTipoVeiculo.setLayout(jPanelTipoVeiculoLayout);
        jPanelTipoVeiculoLayout.setHorizontalGroup(
            jPanelTipoVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTipoVeiculoLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPaneTipoVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelTipoVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonExcluirTipoVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelTipoVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButtonEditarTipoVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonAdicionarTipoVeiculo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTipoVeiculoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTipoVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTipoVeiculoLayout.createSequentialGroup()
                        .addGroup(jPanelTipoVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelTipoVeiculoLayout.createSequentialGroup()
                                .addComponent(jLabelPesquisaTipoVeiculo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxPesquisaTipoVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextFieldPesquisaTipoVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonPesquisaTipoVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))
                    .addComponent(jButtonSair, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanelTipoVeiculoLayout.setVerticalGroup(
            jPanelTipoVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTipoVeiculoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonSair, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jPanelTipoVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPesquisaTipoVeiculo)
                    .addComponent(jComboBoxPesquisaTipoVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelTipoVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldPesquisaTipoVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPesquisaTipoVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelTipoVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneTipoVeiculo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTipoVeiculoLayout.createSequentialGroup()
                        .addComponent(jButtonAdicionarTipoVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonEditarTipoVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonExcluirTipoVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40))
        );

        jPanelMenu.setBackground(new java.awt.Color(81, 81, 81));
        jPanelMenu.setForeground(new java.awt.Color(169, 203, 115));
        jPanelMenu.setPreferredSize(new java.awt.Dimension(180, 600));

        btnHome.setBackground(new java.awt.Color(81, 81, 81));
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnHomeMousePressed(evt);
            }
        });

        jLabelBtnHome.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabelBtnHome.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBtnHome.setText("Principal");

        javax.swing.GroupLayout btnHomeLayout = new javax.swing.GroupLayout(btnHome);
        btnHome.setLayout(btnHomeLayout);
        btnHomeLayout.setHorizontalGroup(
            btnHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBtnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
        );
        btnHomeLayout.setVerticalGroup(
            btnHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBtnHome, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnListaOcorrencia.setBackground(new java.awt.Color(81, 81, 81));
        btnListaOcorrencia.setPreferredSize(new java.awt.Dimension(180, 50));
        btnListaOcorrencia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnListaOcorrenciaMousePressed(evt);
            }
        });

        jLabelBtnListaOcorrencia.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabelBtnListaOcorrencia.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBtnListaOcorrencia.setText("Ocorrências");

        javax.swing.GroupLayout btnListaOcorrenciaLayout = new javax.swing.GroupLayout(btnListaOcorrencia);
        btnListaOcorrencia.setLayout(btnListaOcorrenciaLayout);
        btnListaOcorrenciaLayout.setHorizontalGroup(
            btnListaOcorrenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnListaOcorrenciaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBtnListaOcorrencia, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );
        btnListaOcorrenciaLayout.setVerticalGroup(
            btnListaOcorrenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnListaOcorrenciaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBtnListaOcorrencia, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnListaSalvamento.setBackground(new java.awt.Color(81, 81, 81));
        btnListaSalvamento.setPreferredSize(new java.awt.Dimension(180, 50));
        btnListaSalvamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnListaSalvamentoMousePressed(evt);
            }
        });

        jLabelBtnListaSalvamento.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabelBtnListaSalvamento.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBtnListaSalvamento.setText("Salvamentos");

        javax.swing.GroupLayout btnListaSalvamentoLayout = new javax.swing.GroupLayout(btnListaSalvamento);
        btnListaSalvamento.setLayout(btnListaSalvamentoLayout);
        btnListaSalvamentoLayout.setHorizontalGroup(
            btnListaSalvamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnListaSalvamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBtnListaSalvamento, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );
        btnListaSalvamentoLayout.setVerticalGroup(
            btnListaSalvamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnListaSalvamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBtnListaSalvamento, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnListaAbrigo.setBackground(new java.awt.Color(81, 81, 81));
        btnListaAbrigo.setPreferredSize(new java.awt.Dimension(180, 50));
        btnListaAbrigo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnListaAbrigoMousePressed(evt);
            }
        });

        jLabelBtnListaAbrigo.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabelBtnListaAbrigo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBtnListaAbrigo.setText("Abrigos");

        javax.swing.GroupLayout btnListaAbrigoLayout = new javax.swing.GroupLayout(btnListaAbrigo);
        btnListaAbrigo.setLayout(btnListaAbrigoLayout);
        btnListaAbrigoLayout.setHorizontalGroup(
            btnListaAbrigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnListaAbrigoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBtnListaAbrigo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );
        btnListaAbrigoLayout.setVerticalGroup(
            btnListaAbrigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnListaAbrigoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBtnListaAbrigo, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnListaVeiculo.setBackground(new java.awt.Color(81, 81, 81));
        btnListaVeiculo.setPreferredSize(new java.awt.Dimension(180, 50));
        btnListaVeiculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnListaVeiculoMousePressed(evt);
            }
        });

        jLabelBtnListaVeiculo.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabelBtnListaVeiculo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBtnListaVeiculo.setText("Veiculos");

        javax.swing.GroupLayout btnListaVeiculoLayout = new javax.swing.GroupLayout(btnListaVeiculo);
        btnListaVeiculo.setLayout(btnListaVeiculoLayout);
        btnListaVeiculoLayout.setHorizontalGroup(
            btnListaVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnListaVeiculoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBtnListaVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );
        btnListaVeiculoLayout.setVerticalGroup(
            btnListaVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnListaVeiculoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBtnListaVeiculo, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnListaDadosGerais.setBackground(new java.awt.Color(81, 81, 81));
        btnListaDadosGerais.setPreferredSize(new java.awt.Dimension(180, 50));
        btnListaDadosGerais.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnListaDadosGeraisMousePressed(evt);
            }
        });

        jLabelBtnDadosGerais.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabelBtnDadosGerais.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBtnDadosGerais.setText("Dados Gerais");

        javax.swing.GroupLayout btnListaDadosGeraisLayout = new javax.swing.GroupLayout(btnListaDadosGerais);
        btnListaDadosGerais.setLayout(btnListaDadosGeraisLayout);
        btnListaDadosGeraisLayout.setHorizontalGroup(
            btnListaDadosGeraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnListaDadosGeraisLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBtnDadosGerais)
                .addContainerGap(67, Short.MAX_VALUE))
        );
        btnListaDadosGeraisLayout.setVerticalGroup(
            btnListaDadosGeraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnListaDadosGeraisLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBtnDadosGerais, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelHome.setForeground(new java.awt.Color(255, 255, 255));
        jPanelHome.setPreferredSize(new java.awt.Dimension(620, 600));
        jPanelHome.setRequestFocusEnabled(false);

        javax.swing.GroupLayout jPanelHomeLayout = new javax.swing.GroupLayout(jPanelHome);
        jPanelHome.setLayout(jPanelHomeLayout);
        jPanelHomeLayout.setHorizontalGroup(
            jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );
        jPanelHomeLayout.setVerticalGroup(
            jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 588, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelMenuLayout = new javax.swing.GroupLayout(jPanelMenu);
        jPanelMenu.setLayout(jPanelMenuLayout);
        jPanelMenuLayout.setHorizontalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuLayout.createSequentialGroup()
                .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMenuLayout.createSequentialGroup()
                        .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnListaOcorrencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnListaSalvamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnListaAbrigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnListaVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnListaDadosGerais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMenuLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        jPanelMenuLayout.setVerticalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuLayout.createSequentialGroup()
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnListaOcorrencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnListaSalvamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnListaAbrigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnListaVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnListaDadosGerais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanelHome, 588, 588, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanelTipoVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelTipoVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEditarTipoVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarTipoVeiculoActionPerformed
        if (jTableTipoVeiculo.getSelectedRow() > -1) {

            int id = Integer.parseInt(jTableTipoVeiculo.getValueAt(jTableTipoVeiculo.getSelectedRow(), 0).toString());
            TipoVeiculo tv = new TipoVeiculoDAO().buscarTipoVeiculoPorId(id);
            new JFrameCadastroTipoVeiculo(tv).setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Selecione algo para editar");
        }
        
    }//GEN-LAST:event_jButtonEditarTipoVeiculoActionPerformed

    private void jButtonAdicionarTipoVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarTipoVeiculoActionPerformed
        new JFrameCadastroTipoVeiculo().setVisible(true);
    }//GEN-LAST:event_jButtonAdicionarTipoVeiculoActionPerformed

    private void jButtonExcluirTipoVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirTipoVeiculoActionPerformed
        if (jTableTipoVeiculo.getSelectedRow() > -1) {
            int codTipoVeiculo = Integer.parseInt(jTableTipoVeiculo.getValueAt(jTableTipoVeiculo.getSelectedRow(), 0).toString());
            int excluido = new TipoVeiculoDAO().excluir(codTipoVeiculo);
            if (excluido != Utilitarios.NAO_FOI_POSSIVEL_EXCLUIR) {
                popularListaTipoVeiculo();
                JOptionPane.showMessageDialog(null, "Tipo de Veiculo excluido com sucesso");
            } else {
                JOptionPane.showMessageDialog(null, "Não foi possível excluir a Tipo de Veiculo");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecione algo para excluir");
        }
      
        
        
    }//GEN-LAST:event_jButtonExcluirTipoVeiculoActionPerformed

    private void jButtonPesquisaTipoVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisaTipoVeiculoActionPerformed
        String coluna = jComboBoxPesquisaTipoVeiculo.getSelectedItem().toString();
        String valorPesquisar = jTextFieldPesquisaTipoVeiculo.getText();
        popularListaTipoVeiculoPorPesquisa(coluna, valorPesquisar);
    }//GEN-LAST:event_jButtonPesquisaTipoVeiculoActionPerformed

    private void jComboBoxPesquisaTipoVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPesquisaTipoVeiculoActionPerformed
        //        String coluna = "";

    }//GEN-LAST:event_jComboBoxPesquisaTipoVeiculoActionPerformed

    private void jTextFieldPesquisaTipoVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPesquisaTipoVeiculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPesquisaTipoVeiculoActionPerformed

    private void btnListaOcorrenciaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListaOcorrenciaMousePressed
        new JFrameListaOcorrencia().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnListaOcorrenciaMousePressed

    private void btnListaSalvamentoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListaSalvamentoMousePressed
        new JFrameListaSalvamento().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnListaSalvamentoMousePressed

    private void btnListaAbrigoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListaAbrigoMousePressed
        new JFrameListaAbrigo().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnListaAbrigoMousePressed

    private void btnListaVeiculoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListaVeiculoMousePressed
        new JFrameListaVeiculo().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnListaVeiculoMousePressed

    private void btnListaDadosGeraisMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListaDadosGeraisMousePressed
        new JFrameDadosGerais().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnListaDadosGeraisMousePressed

    private void btnHomeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMousePressed
        new JFrameTelaInicial().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnHomeMousePressed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonSairActionPerformed
                                 

          
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameListaTipoVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameListaTipoVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameListaTipoVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameListaTipoVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameListaTipoVeiculo().setVisible(true);
            }
        });
    }
    
    public void popularListaTipoVeiculoPorPesquisa(String coluna, String valor) {
        DefaultTableModel modelo = (DefaultTableModel) jTableTipoVeiculo.getModel();
        ArrayList<TipoVeiculo> tiposVeiculos = new TipoVeiculoDAO().pesquisarTipoVeiculo(coluna, valor);
        modelo.setRowCount(0);
        for (TipoVeiculo tv : tiposVeiculos) {
            modelo.addRow(new Object[]{
                tv.getIdTipoVeiculo(),
                tv.getNomeTipoVeiculo()
            });
        }
    }
    public void popularListaTipoVeiculo(){
        DefaultTableModel modelo = (DefaultTableModel) jTableTipoVeiculo.getModel();
        ArrayList<TipoVeiculo> tiposVeiculos = new TipoVeiculoDAO().retornarListaTipoVeiculo();
        modelo.setRowCount(0);
         for (TipoVeiculo tipoVeiculo : tiposVeiculos) {
            modelo.addRow(new Object[]{
                tipoVeiculo.getIdTipoVeiculo(), 
                tipoVeiculo.getNomeTipoVeiculo()
            });
        }
    
    }
    private void formWindowActivated(java.awt.event.WindowEvent evt) {                                     
        popularListaTipoVeiculo();
    } 
    
                                       


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnHome;
    private javax.swing.JPanel btnListaAbrigo;
    private javax.swing.JPanel btnListaDadosGerais;
    private javax.swing.JPanel btnListaOcorrencia;
    private javax.swing.JPanel btnListaSalvamento;
    private javax.swing.JPanel btnListaVeiculo;
    private javax.swing.JButton jButtonAdicionarTipoVeiculo;
    private javax.swing.JButton jButtonEditarTipoVeiculo;
    private javax.swing.JButton jButtonExcluirTipoVeiculo;
    private javax.swing.JButton jButtonPesquisaTipoVeiculo;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JComboBox jComboBoxPesquisaTipoVeiculo;
    private javax.swing.JLabel jLabelBtnDadosGerais;
    private javax.swing.JLabel jLabelBtnHome;
    private javax.swing.JLabel jLabelBtnListaAbrigo;
    private javax.swing.JLabel jLabelBtnListaOcorrencia;
    private javax.swing.JLabel jLabelBtnListaSalvamento;
    private javax.swing.JLabel jLabelBtnListaVeiculo;
    private javax.swing.JLabel jLabelPesquisaTipoVeiculo;
    private javax.swing.JPanel jPanelHome;
    private javax.swing.JPanel jPanelMenu;
    private javax.swing.JPanel jPanelTipoVeiculo;
    private javax.swing.JScrollPane jScrollPaneTipoVeiculo;
    private javax.swing.JTable jTableTipoVeiculo;
    private javax.swing.JTextField jTextFieldPesquisaTipoVeiculo;
    // End of variables declaration//GEN-END:variables

    
}
