
package view;

import dao.AbrigoDAO;
import dao.VeiculoDAO;
import database.Utilitarios;
import javax.swing.JOptionPane;
import model.Abrigo;

/**
 *
 * @author Alunos  Talita vitoria, Felipe Tobias, Iara Oliveira e Vinicius donschen
 */
public class JFrameCadastroAbrigo extends javax.swing.JFrame {

    /**
     * Creates new form JFrameCadadstroAbrigo
     */
    public JFrameCadastroAbrigo() {
        initComponents();
    }
    
    JFrameCadastroAbrigo(Abrigo abrigo){
        initComponents();
        jLabelNumId.setText(String.valueOf(abrigo.getIdAbrigo()));
        jTextFieldNome.setText(abrigo.getNomeAbrigo());
        jTextLocal.setText(abrigo.getLocalAbrigo());
        jTextResponsavel.setText(abrigo.getResponsavelAbrigo());
        jComboBoxLotacao.setSelectedItem(abrigo);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelCadastroAbrigos = new javax.swing.JLabel();
        jLabelNome = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jLabelLocal = new javax.swing.JLabel();
        jTextLocal = new javax.swing.JTextField();
        jLabelResponsavel = new javax.swing.JLabel();
        jTextResponsavel = new javax.swing.JTextField();
        jLabelLotacao = new javax.swing.JLabel();
        jComboBoxLotacao = new javax.swing.JComboBox();
        jButtonSalvarAbrigo = new javax.swing.JButton();
        jLabelIdAbrigo = new javax.swing.JLabel();
        jLabelNumId = new javax.swing.JLabel();
        jButtonCancelarOcorrencia = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelCadastroAbrigos.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabelCadastroAbrigos.setForeground(new java.awt.Color(81, 81, 81));
        jLabelCadastroAbrigos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCadastroAbrigos.setText("CADASTRO de ABRIGOS");
        jLabelCadastroAbrigos.setFocusable(false);

        jLabelNome.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabelNome.setForeground(new java.awt.Color(81, 81, 81));
        jLabelNome.setText("Nome");

        jTextFieldNome.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jTextFieldNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeActionPerformed(evt);
            }
        });

        jLabelLocal.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabelLocal.setForeground(new java.awt.Color(81, 81, 81));
        jLabelLocal.setText("Local");

        jTextLocal.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jTextLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextLocalActionPerformed(evt);
            }
        });

        jLabelResponsavel.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabelResponsavel.setForeground(new java.awt.Color(81, 81, 81));
        jLabelResponsavel.setText("Responsável");

        jTextResponsavel.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        jLabelLotacao.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabelLotacao.setForeground(new java.awt.Color(81, 81, 81));
        jLabelLotacao.setText("Lotação");

        jComboBoxLotacao.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jComboBoxLotacao.setForeground(new java.awt.Color(81, 81, 81));
        jComboBoxLotacao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40" }));
        jComboBoxLotacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxLotacaoActionPerformed(evt);
            }
        });

        jButtonSalvarAbrigo.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jButtonSalvarAbrigo.setForeground(new java.awt.Color(81, 81, 81));
        jButtonSalvarAbrigo.setText("Salvar");
        jButtonSalvarAbrigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarAbrigoActionPerformed(evt);
            }
        });

        jLabelIdAbrigo.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N

        jLabelNumId.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        jButtonCancelarOcorrencia.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jButtonCancelarOcorrencia.setForeground(new java.awt.Color(81, 81, 81));
        jButtonCancelarOcorrencia.setText("Cancelar");
        jButtonCancelarOcorrencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarOcorrenciaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelIdAbrigo, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelCadastroAbrigos)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelNumId, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(128, 128, 128))
                                    .addComponent(jLabelLocal)
                                    .addComponent(jLabelResponsavel)
                                    .addComponent(jLabelLotacao)
                                    .addComponent(jComboBoxLotacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jTextResponsavel, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextLocal, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextFieldNome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(354, Short.MAX_VALUE)
                .addComponent(jButtonSalvarAbrigo, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCancelarOcorrencia, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelIdAbrigo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCadastroAbrigos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jLabelNumId, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelLocal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextLocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelResponsavel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelLotacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBoxLotacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSalvarAbrigo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCancelarOcorrencia, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeActionPerformed

    private void jTextLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextLocalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextLocalActionPerformed

    private void jComboBoxLotacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxLotacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxLotacaoActionPerformed


    private void jButtonSalvarAbrigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarAbrigoActionPerformed
        if(jTextFieldNome.getText().length() == 0){
            JOptionPane.showMessageDialog(null, "Nome não pode ser vazio!!");
            jTextFieldNome.requestFocus();
            return;
        }
        
        if(jTextLocal.getText().length() == 0){
            JOptionPane.showMessageDialog(null, "Local não pode ser vazio!!");
            return;
        }
        
        if(jTextResponsavel.getText().length() == 0){
            JOptionPane.showMessageDialog(null, "Responsável não pode ser vazio!!");
        }
        
        if(Integer.parseInt(jComboBoxLotacao.getSelectedItem().toString()) == 0){
            JOptionPane.showMessageDialog(null, "Lotação não pode ser vazio!!");
            jComboBoxLotacao.requestFocus();
            return;
        }
        
            Abrigo abrigo = new Abrigo();
            abrigo.setNomeAbrigo(jTextFieldNome.getText());
            abrigo.setLocalAbrigo(jTextLocal.getText());
            abrigo.setResponsavelAbrigo(jTextResponsavel.getText());
            abrigo.setLotacaoAbrigo(Integer.parseInt(jComboBoxLotacao.getSelectedItem().toString()));
        
            if (jLabelNumId.getText().equals("")) {
                int codInserir = new AbrigoDAO().inserir(abrigo);
                if (codInserir == Utilitarios.NAO_FOI_POSSIVEL_INSERIR) {
                    JOptionPane.showMessageDialog(null, "Não foi Possível Inserir");
                }else {
                    abrigo.setIdAbrigo(codInserir);
                    jLabelNumId.setText(String.valueOf(codInserir));
                    JOptionPane.showMessageDialog(null, "Abrigo Inserido com Sucesso");
                }
            }else {
                int id = Integer.parseInt(jLabelNumId.getText());
                abrigo.setIdAbrigo(id);
                int codAlteracao = new AbrigoDAO().alterar(abrigo);
                if (codAlteracao == Utilitarios.NAO_FOI_POSSIVEL_ALTERAR) {
                    JOptionPane.showMessageDialog(null, "Não foi Possível Alterar");
                }else {
                    JOptionPane.showMessageDialog(null, "Abrigo Alterado com Sucesso");
                }
            }

            dispose(); 
        
        
        
        
    }//GEN-LAST:event_jButtonSalvarAbrigoActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
         
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonCancelarOcorrenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarOcorrenciaActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonCancelarOcorrenciaActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameCadastroAbrigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameCadastroAbrigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameCadastroAbrigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameCadastroAbrigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameCadastroAbrigo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelarOcorrencia;
    private javax.swing.JButton jButtonSalvarAbrigo;
    private javax.swing.JComboBox jComboBoxLotacao;
    private javax.swing.JLabel jLabelCadastroAbrigos;
    private javax.swing.JLabel jLabelIdAbrigo;
    private javax.swing.JLabel jLabelLocal;
    private javax.swing.JLabel jLabelLotacao;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelNumId;
    private javax.swing.JLabel jLabelResponsavel;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextLocal;
    private javax.swing.JTextField jTextResponsavel;
    // End of variables declaration//GEN-END:variables
}
