package view;

import dao.AbrigoDAO;
import dao.OcorrenciaDAO;
import dao.SalvamentoDAO;
import database.Utilitarios;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import model.Abrigo;
import model.Ocorrencia;
import model.Salvamento;

/**
 *
 * @author Alunos Talita vitoria, Felipe Tobias, Iara Oliveira e Vinicius
 * donschen
 */
public class JFrameListaOcorrencia extends javax.swing.JFrame {

    private int linhaSelecionada = -1;

    /**
     * Creates new form JFrameCadastroOcorrencia
     */
    public JFrameListaOcorrencia() {
        initComponents();
        popularListaOcorrencia();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelListaOcorrencias = new javax.swing.JPanel();
        jButtonAdicionarOcorrencia = new javax.swing.JButton();
        jButtonAdicionarSalvamento = new javax.swing.JButton();
        jTextFieldPesquisaOcorrencia = new javax.swing.JTextField();
        jLabelPesquisaOcorrencia = new javax.swing.JLabel();
        jComboBoxPesquisaOcorrencia = new javax.swing.JComboBox();
        jButtonEditarOcorrencia = new javax.swing.JButton();
        jScrollPaneOcorrencia = new javax.swing.JScrollPane();
        jTableOcorrencia = new javax.swing.JTable();
        jButtonPesquisaOcorrencia = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jLabelListaOcorrencia = new javax.swing.JLabel();
        jPanelMenu = new javax.swing.JPanel();
        btnHome = new javax.swing.JPanel();
        jLabelBtnHome = new javax.swing.JLabel();
        btnListaOcorrencia = new javax.swing.JPanel();
        jLabelBtnListaOcorrencia = new javax.swing.JLabel();
        btnListaSalvamento = new javax.swing.JPanel();
        jLabelBtnListaSalvamento = new javax.swing.JLabel();
        btnListaAbrigo = new javax.swing.JPanel();
        jLabelBtnListaAbrigo = new javax.swing.JLabel();
        btnListaVeiculo = new javax.swing.JPanel();
        jLabelBtnListaVeiculo = new javax.swing.JLabel();
        btnListaDadosGerais = new javax.swing.JPanel();
        jLabelBtnDadosGerais = new javax.swing.JLabel();
        jPanelHome = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ocorrências");
        setBounds(new java.awt.Rectangle(800, 600, 0, 0));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jButtonAdicionarOcorrencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/add-515151-64px.png"))); // NOI18N
        jButtonAdicionarOcorrencia.setToolTipText("Adicionar nova ocorrência");
        jButtonAdicionarOcorrencia.setBorderPainted(false);
        jButtonAdicionarOcorrencia.setContentAreaFilled(false);
        jButtonAdicionarOcorrencia.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/add-a9cb73-64px.png"))); // NOI18N
        jButtonAdicionarOcorrencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarOcorrenciaActionPerformed(evt);
            }
        });

        jButtonAdicionarSalvamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/check-515151-64px.png"))); // NOI18N
        jButtonAdicionarSalvamento.setToolTipText("Marcar uma ocorrência como atendida");
        jButtonAdicionarSalvamento.setBorderPainted(false);
        jButtonAdicionarSalvamento.setContentAreaFilled(false);
        jButtonAdicionarSalvamento.setPreferredSize(new java.awt.Dimension(40, 40));
        jButtonAdicionarSalvamento.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/check-a9cb73-64px.png"))); // NOI18N
        jButtonAdicionarSalvamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarSalvamentoActionPerformed(evt);
            }
        });

        jTextFieldPesquisaOcorrencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPesquisaOcorrenciaActionPerformed(evt);
            }
        });

        jLabelPesquisaOcorrencia.setText("Pesquisar por:");

        jComboBoxPesquisaOcorrencia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Código", "Data", "Hora", "Local" }));
        jComboBoxPesquisaOcorrencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPesquisaOcorrenciaActionPerformed(evt);
            }
        });

        jButtonEditarOcorrencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/edit-515151-64px.png"))); // NOI18N
        jButtonEditarOcorrencia.setToolTipText("Editar ocorrência já existente");
        jButtonEditarOcorrencia.setBorderPainted(false);
        jButtonEditarOcorrencia.setContentAreaFilled(false);
        jButtonEditarOcorrencia.setDisabledIcon(null);
        jButtonEditarOcorrencia.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/edit-a9cb73-64px.png"))); // NOI18N
        jButtonEditarOcorrencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarOcorrenciaActionPerformed(evt);
            }
        });

        jScrollPaneOcorrencia.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPaneOcorrencia.setViewportBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPaneOcorrencia.setPreferredSize(new java.awt.Dimension(500, 400));

        jTableOcorrencia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Data", "Hora", "Local"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableOcorrencia.setGridColor(new java.awt.Color(81, 81, 81));
        jTableOcorrencia.setIntercellSpacing(new java.awt.Dimension(1, 2));
        jTableOcorrencia.setMaximumSize(new java.awt.Dimension(500, 400));
        jTableOcorrencia.setMinimumSize(new java.awt.Dimension(500, 400));
        jTableOcorrencia.setPreferredSize(new java.awt.Dimension(500, 400));
        jTableOcorrencia.setSelectionBackground(new java.awt.Color(169, 203, 115));
        jTableOcorrencia.setShowVerticalLines(false);
        jTableOcorrencia.getTableHeader().setResizingAllowed(false);
        jTableOcorrencia.getTableHeader().setReorderingAllowed(false);
        jScrollPaneOcorrencia.setViewportView(jTableOcorrencia);

        jButtonPesquisaOcorrencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/search-515151-32px.png"))); // NOI18N
        jButtonPesquisaOcorrencia.setToolTipText("Pesquisar Ocorrência");
        jButtonPesquisaOcorrencia.setBorderPainted(false);
        jButtonPesquisaOcorrencia.setContentAreaFilled(false);
        jButtonPesquisaOcorrencia.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/search-a9cb73-32px.png"))); // NOI18N
        jButtonPesquisaOcorrencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisaOcorrenciaActionPerformed(evt);
            }
        });

        jButtonSair.setBackground(new java.awt.Color(81, 81, 81));
        jButtonSair.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jButtonSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/cancel-515151-64px.png"))); // NOI18N
        jButtonSair.setToolTipText("Sair");
        jButtonSair.setBorderPainted(false);
        jButtonSair.setContentAreaFilled(false);
        jButtonSair.setPreferredSize(new java.awt.Dimension(40, 40));
        jButtonSair.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/cancel-a9cb73-64px.png"))); // NOI18N
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        jLabelListaOcorrencia.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabelListaOcorrencia.setForeground(new java.awt.Color(81, 81, 81));
        jLabelListaOcorrencia.setText("LISTA de OCORRÊNCIAS");

        javax.swing.GroupLayout jPanelListaOcorrenciasLayout = new javax.swing.GroupLayout(jPanelListaOcorrencias);
        jPanelListaOcorrencias.setLayout(jPanelListaOcorrenciasLayout);
        jPanelListaOcorrenciasLayout.setHorizontalGroup(
            jPanelListaOcorrenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListaOcorrenciasLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanelListaOcorrenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelListaOcorrenciasLayout.createSequentialGroup()
                        .addGroup(jPanelListaOcorrenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelListaOcorrenciasLayout.createSequentialGroup()
                                .addComponent(jLabelPesquisaOcorrencia)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxPesquisaOcorrencia, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextFieldPesquisaOcorrencia, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonPesquisaOcorrencia, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelListaOcorrenciasLayout.createSequentialGroup()
                        .addComponent(jLabelListaOcorrencia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonSair, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanelListaOcorrenciasLayout.createSequentialGroup()
                        .addComponent(jScrollPaneOcorrencia, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelListaOcorrenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonEditarOcorrencia, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonAdicionarOcorrencia, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonAdicionarSalvamento, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 44, Short.MAX_VALUE))))
        );
        jPanelListaOcorrenciasLayout.setVerticalGroup(
            jPanelListaOcorrenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListaOcorrenciasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelListaOcorrenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonSair, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelListaOcorrencia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelListaOcorrenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelListaOcorrenciasLayout.createSequentialGroup()
                        .addGroup(jPanelListaOcorrenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelPesquisaOcorrencia)
                            .addComponent(jComboBoxPesquisaOcorrencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldPesquisaOcorrencia, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonPesquisaOcorrencia, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelListaOcorrenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPaneOcorrencia, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelListaOcorrenciasLayout.createSequentialGroup()
                        .addComponent(jButtonAdicionarSalvamento, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAdicionarOcorrencia, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonEditarOcorrencia, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40))
        );

        jPanelMenu.setBackground(new java.awt.Color(81, 81, 81));
        jPanelMenu.setForeground(new java.awt.Color(169, 203, 115));
        jPanelMenu.setPreferredSize(new java.awt.Dimension(180, 600));

        btnHome.setBackground(new java.awt.Color(81, 81, 81));
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnHomeMousePressed(evt);
            }
        });

        jLabelBtnHome.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabelBtnHome.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBtnHome.setText("Principal");

        javax.swing.GroupLayout btnHomeLayout = new javax.swing.GroupLayout(btnHome);
        btnHome.setLayout(btnHomeLayout);
        btnHomeLayout.setHorizontalGroup(
            btnHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBtnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
        );
        btnHomeLayout.setVerticalGroup(
            btnHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBtnHome, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnListaOcorrencia.setBackground(new java.awt.Color(97, 97, 97));
        btnListaOcorrencia.setPreferredSize(new java.awt.Dimension(180, 50));

        jLabelBtnListaOcorrencia.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabelBtnListaOcorrencia.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBtnListaOcorrencia.setText("Ocorrências");

        javax.swing.GroupLayout btnListaOcorrenciaLayout = new javax.swing.GroupLayout(btnListaOcorrencia);
        btnListaOcorrencia.setLayout(btnListaOcorrenciaLayout);
        btnListaOcorrenciaLayout.setHorizontalGroup(
            btnListaOcorrenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnListaOcorrenciaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBtnListaOcorrencia, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );
        btnListaOcorrenciaLayout.setVerticalGroup(
            btnListaOcorrenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnListaOcorrenciaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBtnListaOcorrencia, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnListaSalvamento.setBackground(new java.awt.Color(81, 81, 81));
        btnListaSalvamento.setPreferredSize(new java.awt.Dimension(180, 50));
        btnListaSalvamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnListaSalvamentoMousePressed(evt);
            }
        });

        jLabelBtnListaSalvamento.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabelBtnListaSalvamento.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBtnListaSalvamento.setText("Salvamentos");

        javax.swing.GroupLayout btnListaSalvamentoLayout = new javax.swing.GroupLayout(btnListaSalvamento);
        btnListaSalvamento.setLayout(btnListaSalvamentoLayout);
        btnListaSalvamentoLayout.setHorizontalGroup(
            btnListaSalvamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnListaSalvamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBtnListaSalvamento, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );
        btnListaSalvamentoLayout.setVerticalGroup(
            btnListaSalvamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnListaSalvamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBtnListaSalvamento, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnListaAbrigo.setBackground(new java.awt.Color(81, 81, 81));
        btnListaAbrigo.setPreferredSize(new java.awt.Dimension(180, 50));
        btnListaAbrigo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnListaAbrigoMousePressed(evt);
            }
        });

        jLabelBtnListaAbrigo.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabelBtnListaAbrigo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBtnListaAbrigo.setText("Abrigos");

        javax.swing.GroupLayout btnListaAbrigoLayout = new javax.swing.GroupLayout(btnListaAbrigo);
        btnListaAbrigo.setLayout(btnListaAbrigoLayout);
        btnListaAbrigoLayout.setHorizontalGroup(
            btnListaAbrigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnListaAbrigoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBtnListaAbrigo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );
        btnListaAbrigoLayout.setVerticalGroup(
            btnListaAbrigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnListaAbrigoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBtnListaAbrigo, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnListaVeiculo.setBackground(new java.awt.Color(81, 81, 81));
        btnListaVeiculo.setPreferredSize(new java.awt.Dimension(180, 50));
        btnListaVeiculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnListaVeiculoMousePressed(evt);
            }
        });

        jLabelBtnListaVeiculo.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabelBtnListaVeiculo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBtnListaVeiculo.setText("Veiculos");

        javax.swing.GroupLayout btnListaVeiculoLayout = new javax.swing.GroupLayout(btnListaVeiculo);
        btnListaVeiculo.setLayout(btnListaVeiculoLayout);
        btnListaVeiculoLayout.setHorizontalGroup(
            btnListaVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnListaVeiculoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBtnListaVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );
        btnListaVeiculoLayout.setVerticalGroup(
            btnListaVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnListaVeiculoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBtnListaVeiculo, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnListaDadosGerais.setBackground(new java.awt.Color(81, 81, 81));
        btnListaDadosGerais.setPreferredSize(new java.awt.Dimension(180, 50));
        btnListaDadosGerais.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnListaDadosGeraisMousePressed(evt);
            }
        });

        jLabelBtnDadosGerais.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabelBtnDadosGerais.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBtnDadosGerais.setText("Dados Gerais");

        javax.swing.GroupLayout btnListaDadosGeraisLayout = new javax.swing.GroupLayout(btnListaDadosGerais);
        btnListaDadosGerais.setLayout(btnListaDadosGeraisLayout);
        btnListaDadosGeraisLayout.setHorizontalGroup(
            btnListaDadosGeraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnListaDadosGeraisLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBtnDadosGerais)
                .addContainerGap(67, Short.MAX_VALUE))
        );
        btnListaDadosGeraisLayout.setVerticalGroup(
            btnListaDadosGeraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnListaDadosGeraisLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBtnDadosGerais, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelHome.setForeground(new java.awt.Color(255, 255, 255));
        jPanelHome.setPreferredSize(new java.awt.Dimension(620, 600));
        jPanelHome.setRequestFocusEnabled(false);

        javax.swing.GroupLayout jPanelHomeLayout = new javax.swing.GroupLayout(jPanelHome);
        jPanelHome.setLayout(jPanelHomeLayout);
        jPanelHomeLayout.setHorizontalGroup(
            jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );
        jPanelHomeLayout.setVerticalGroup(
            jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelMenuLayout = new javax.swing.GroupLayout(jPanelMenu);
        jPanelMenu.setLayout(jPanelMenuLayout);
        jPanelMenuLayout.setHorizontalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuLayout.createSequentialGroup()
                .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMenuLayout.createSequentialGroup()
                        .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnListaOcorrencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnListaSalvamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnListaAbrigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnListaVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnListaDadosGerais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMenuLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        jPanelMenuLayout.setVerticalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuLayout.createSequentialGroup()
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnListaOcorrencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnListaSalvamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnListaAbrigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnListaVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnListaDadosGerais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanelHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanelListaOcorrencias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelListaOcorrencias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        popularListaOcorrencia();

    }//GEN-LAST:event_formWindowActivated

    private void jButtonAdicionarOcorrenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarOcorrenciaActionPerformed
        new JFrameCadastroOcorrencia().setVisible(true);
    }//GEN-LAST:event_jButtonAdicionarOcorrenciaActionPerformed

    private void jButtonAdicionarSalvamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarSalvamentoActionPerformed
        if (jTableOcorrencia.getSelectedRow() > -1) {

            int codigoOcorrencia = Integer.parseInt(jTableOcorrencia.getValueAt(jTableOcorrencia.getSelectedRow(), 0).toString());

            Salvamento s = new Salvamento();
            Ocorrencia o = new OcorrenciaDAO().buscarOcorrenciaPorId(codigoOcorrencia);
            s.setFKOcorrencia(o);
            new JFrameCadastroSalvamento(s).setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um salvamento ja realizado");
        }
    }//GEN-LAST:event_jButtonAdicionarSalvamentoActionPerformed

    private void jTextFieldPesquisaOcorrenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPesquisaOcorrenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPesquisaOcorrenciaActionPerformed

    private void jComboBoxPesquisaOcorrenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPesquisaOcorrenciaActionPerformed
        //        String coluna = "";
    }//GEN-LAST:event_jComboBoxPesquisaOcorrenciaActionPerformed

    private void jButtonEditarOcorrenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarOcorrenciaActionPerformed
        if (jTableOcorrencia.getSelectedRow() > -1) {

            int id = Integer.parseInt(jTableOcorrencia.getValueAt(jTableOcorrencia.getSelectedRow(), 0).toString());
            Ocorrencia o = new OcorrenciaDAO().buscarOcorrenciaPorId(id);
            new JFrameCadastroOcorrencia(o).setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Selecione algo para editar");
        }
    }//GEN-LAST:event_jButtonEditarOcorrenciaActionPerformed

    private void jButtonPesquisaOcorrenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisaOcorrenciaActionPerformed
        String coluna = jComboBoxPesquisaOcorrencia.getSelectedItem().toString();
        String valorPesquisar = jTextFieldPesquisaOcorrencia.getText();
        popularListaOcorrenciaPorPesquisa(coluna, valorPesquisar);
    }//GEN-LAST:event_jButtonPesquisaOcorrenciaActionPerformed

    private void btnListaSalvamentoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListaSalvamentoMousePressed
        new JFrameListaSalvamento().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnListaSalvamentoMousePressed

    private void btnListaAbrigoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListaAbrigoMousePressed
        new JFrameListaAbrigo().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnListaAbrigoMousePressed

    private void btnListaVeiculoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListaVeiculoMousePressed
        new JFrameListaVeiculo().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnListaVeiculoMousePressed

    private void btnListaDadosGeraisMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListaDadosGeraisMousePressed
        new JFrameDadosGerais().setVisible(true);
        dispose();

    }//GEN-LAST:event_btnListaDadosGeraisMousePressed

    private void btnHomeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMousePressed
        new JFrameTelaInicial().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnHomeMousePressed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed

        System.exit(0);
    }//GEN-LAST:event_jButtonSairActionPerformed

    public void clickDaTabela() {
        jTableOcorrencia.getSelectionModel().addListSelectionListener(new ListSelectionListener() {

            @Override
            public void valueChanged(ListSelectionEvent e) {
                jButtonEditarOcorrencia.setEnabled(true);
  
            }
        });
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameListaOcorrencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameListaOcorrencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameListaOcorrencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameListaOcorrencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameListaOcorrencia().setVisible(true);
            }
        });
    }

    
    public void popularListaOcorrenciaPorPesquisa(String coluna, String valor) {
        DefaultTableModel modelo = (DefaultTableModel) jTableOcorrencia.getModel();
        ArrayList<Ocorrencia> ocorrencias = new OcorrenciaDAO().pesquisarOcorrencia(coluna, valor);
        modelo.setRowCount(0);
        for (Ocorrencia ocorrencia : ocorrencias) {
            modelo.addRow(new Object[]{
                ocorrencia.getIdOcorrencia(),
               Utilitarios.retornarPadraoBR( ocorrencia.getDataOcorrencia()),
                ocorrencia.getHoraOcorrencia(),
                ocorrencia.getLocalOcorrencia()
   
            });
        }
    }
    
    public void popularListaOcorrencia() {
        DefaultTableModel modelo = (DefaultTableModel) jTableOcorrencia.getModel();
        ArrayList<Ocorrencia> ocorrencias = new OcorrenciaDAO().retornarListaOcorrencia();
        modelo.setRowCount(0);
        for (Ocorrencia ocorrencia : ocorrencias) {
            modelo.addRow(new Object[]{
                ocorrencia.getIdOcorrencia(),
               Utilitarios.retornarPadraoBR( ocorrencia.getDataOcorrencia()),
                ocorrencia.getHoraOcorrencia(),
                ocorrencia.getLocalOcorrencia()
                
            });
        }
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnHome;
    private javax.swing.JPanel btnListaAbrigo;
    private javax.swing.JPanel btnListaDadosGerais;
    private javax.swing.JPanel btnListaOcorrencia;
    private javax.swing.JPanel btnListaSalvamento;
    private javax.swing.JPanel btnListaVeiculo;
    private javax.swing.JButton jButtonAdicionarOcorrencia;
    private javax.swing.JButton jButtonAdicionarSalvamento;
    private javax.swing.JButton jButtonEditarOcorrencia;
    private javax.swing.JButton jButtonPesquisaOcorrencia;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JComboBox jComboBoxPesquisaOcorrencia;
    private javax.swing.JLabel jLabelBtnDadosGerais;
    private javax.swing.JLabel jLabelBtnHome;
    private javax.swing.JLabel jLabelBtnListaAbrigo;
    private javax.swing.JLabel jLabelBtnListaOcorrencia;
    private javax.swing.JLabel jLabelBtnListaSalvamento;
    private javax.swing.JLabel jLabelBtnListaVeiculo;
    private javax.swing.JLabel jLabelListaOcorrencia;
    private javax.swing.JLabel jLabelPesquisaOcorrencia;
    private javax.swing.JPanel jPanelHome;
    private javax.swing.JPanel jPanelListaOcorrencias;
    private javax.swing.JPanel jPanelMenu;
    private javax.swing.JScrollPane jScrollPaneOcorrencia;
    private javax.swing.JTable jTableOcorrencia;
    private javax.swing.JTextField jTextFieldPesquisaOcorrencia;
    // End of variables declaration//GEN-END:variables
}
